-- Issue #603 WI-05 — the semantic half of the two `mcp_open_*` candidate
-- probes, as a `clickhouse local` fixture.
--
-- The Rust unit tests in `reclaim_mcp_open.rs` assert the *text* of each
-- probe's conjuncts: delete one and a named test fails. They cannot assert what
-- the conjunct does, because that needs a server.
--
-- NOTHING IN `cargo test` RUNS THIS. `the_fixture_files_are_this_builds_
-- statements_verbatim` compares generated strings against the checked-in files
-- here; it starts no ClickHouse. Plan §7.2's `reclaim-orphan` and
-- `reclaim-generation` live gates are where this becomes automated, and they
-- are **unwritten** — grep finds no such test in the tree — not merely unrun.
-- Docker is unavailable on the reference host, so a sandbox could not have run
-- them either. This fixture is what was actually executed, by hand, and it is
-- checked in so the next reader can execute it too.
--
-- Reproduce (ClickHouse 25.12.5.44, the version-matched binary the stack ships):
--
--   CH=~/.local/lib/moraine/clickhouse/current/bin/clickhouse
--   D=$(mktemp -d)
--   "$CH" local --path "$D" --multiquery < fixture.sql
--   "$CH" local --path "$D" --multiquery < expected/orphan.sql
--   "$CH" local --path "$D" --multiquery < expected/retired.sql
--   "$CH" local --path "$D" --multiquery < expected/delete.sql   # deletes, then census
--
-- `expected/delete.sql` runs THIS BUILD's delete statements for every unit the
-- two probes above return, then prints the survivor census. It exists because
-- the deletes are the only statements here that can destroy live data and
-- nothing used to execute one: a predicate that *widened* — appending
-- ` OR session_id = {session}` to the child arm — left the whole workspace
-- green while emptying four generations of L-RETIRE.
--
-- Its DELETEs are generated by instantiating the shipped predicates over the
-- hand-maintained `FIXTURE_UNITS` list, which makes the file blind in the *add*
-- direction on its own: a probe that starts returning a unit the list omits
-- produces a file with no statement for it, and the census below then prints
-- that session as intact for a build that destroys it. Under the pre-P6 probe
-- that is exactly what happened with `A1B 60`. So `expected/delete.sql` now
-- opens with two `throwIf` statements that run THIS BUILD's probes and compare
-- their output to the list, before any delete. On disagreement the file aborts
-- with `FIXTURE_UNITS no longer matches …` and a non-zero exit (ClickHouse
-- reports 139 for an aborted `local --multiquery` run on macOS), having
-- deleted nothing — verified 2026-07-28 by dropping one unit from the expected
-- array and re-running: the census afterwards showed every fixture row intact.
--
-- Expected survivor census (executed 2026-07-28):
--   session_id  headers turns events
--   A1B         2       1     2     <- the two-headers-one-generation live
--                                      snapshot, fully intact (P6)
--   L-FRESH     2       0     0
--   L-NOPTR     2       0     0
--   L-RETIRE    3       0     3     <- generations 50 and 53 collected; the
--                                      live 60, plus 51 and 52, survive
--   L-STALEPTR  2       0     0
--   L-UNPUB     2       0     0
--   o-fresh     0       0     1
--   o-headered  1       0     1
--   o-planned   0       0     1     <- generation 103 (in-flight plan) kept,
--                                      104 collected
--   o-tombstoned 1      0     1
--   and o-collect / o-plandone / o-turnsonly gone entirely.
--
-- The two probe files are `orphan_candidate_sql("moraine", 86400, 512)` and
-- `retired_lineage_candidate_sql("moraine", 86400, 512)` verbatim, with
-- `FORMAT JSONEachRow` swapped for `FORMAT TSVWithNames`.
--
-- Expected orphan output (executed 2026-07-28):
--   o-collect   100  2 events  1 turn
--   o-plandone  105  1 event            (a COMPLETE plan protects nothing)
--   o-planned   104  1 event            (the session's in-flight plan names 103)
--   o-turnsonly 107            1 turn   (a turns-only pair; header-derived
--                                        probes cannot see it at all)
--   and NOT o-headered/101, o-fresh/102, o-planned/103, o-tombstoned/106.
--
-- Expected retirement output (executed 2026-07-28):
--   L-RETIRE 50  1 event 1 turn 1 header
--   L-RETIRE 53                 1 header   (a childless tombstone unit)
--   and NOT L-RETIRE/51 (a reader can still select it), /52 (same lineage —
--   the existing reclaimer owns it), /60 (live), nor anything from L-UNPUB,
--   L-NOPTR, L-FRESH or L-STALEPTR.
--
-- The mutation ledger these cases witness is in the PR description; each row
-- was produced by editing the probe text here and re-running the two commands
-- above.
--
-- ## The DDL below is NOT the schema of record
--
-- "Verbatim" above is a claim about the two probe files and
-- `expected/delete.sql`, not about these `CREATE TABLE`s. Each table here is
-- **reduced to the columns the probes read** — `mcp_open_publication_headers`
-- ships eighteen more columns than the ten below, and
-- `v_current_published_source_generations` is a *view* in production, stood in
-- for here by a table because `clickhouse local` has nothing to derive it
-- from. `sql/027`, `sql/033` and `sql/034` are the schema of record.
--
-- What *is* faithful is every sort key, because a probe's cost and a
-- `ReplacingMergeTree`'s collapse both depend on it: each `ORDER BY` and
-- `PARTITION BY` below is the shipped one for that table. `mcp_open_events`
-- accordingly carries `source_host` — a column no probe reads — purely so its
-- key is `sql/033`'s `(event_uid, slot, source_host, candidate_generation)`
-- and not a three-column abbreviation of it.

CREATE DATABASE IF NOT EXISTS moraine;

CREATE TABLE moraine.mcp_open_events (
  event_uid String, slot UInt8, source_host String, generation UInt64,
  candidate_generation UInt64,
  session_id String, projected_at DateTime64(3) DEFAULT now64(3)
) ENGINE = ReplacingMergeTree(generation)
PARTITION BY cityHash64(event_uid) % 64
ORDER BY (event_uid, slot, source_host, candidate_generation);

CREATE TABLE moraine.mcp_open_turns (
  session_id String, slot UInt8, generation UInt64, turn_seq UInt32,
  candidate_generation UInt64, projected_at DateTime64(3) DEFAULT now64(3)
) ENGINE = ReplacingMergeTree(generation)
PARTITION BY cityHash64(session_id) % 64
ORDER BY (session_id, slot, turn_seq, candidate_generation);

CREATE TABLE moraine.mcp_open_publication_headers (
  session_id String, candidate_publication_id String, slot UInt8, generation UInt64,
  dirty_revision UInt64, tombstone UInt8,
  required_source_heads Array(Tuple(source_host String, source_name String,
    source_file String, source_generation UInt32, publication_revision UInt64)),
  required_heads_fingerprint String, header_revision UInt64,
  prepared_at DateTime64(3) DEFAULT now64(3)
) ENGINE = ReplacingMergeTree(header_revision)
PARTITION BY cityHash64(session_id) % 64
ORDER BY (session_id, candidate_publication_id);

CREATE TABLE moraine.mcp_open_sessions (
  session_id String, slot UInt8, generation UInt64, projected_at DateTime64(3) DEFAULT now64(3)
) ENGINE = ReplacingMergeTree(generation)
ORDER BY (session_id);

CREATE TABLE moraine.mcp_open_dirty_sessions (
  session_id String, dirty_revision UInt64, observed_at DateTime64(3) DEFAULT now64(3)
) ENGINE = ReplacingMergeTree(dirty_revision) ORDER BY (session_id);

CREATE TABLE moraine.mcp_open_backfill_plans (
  session_id String, candidate_publication_id String, slot UInt8,
  candidate_generation UInt64, phase UInt8, plan_revision UInt64
) ENGINE = ReplacingMergeTree(plan_revision) ORDER BY (session_id);

CREATE TABLE moraine.v_current_published_source_generations (
  source_host String, source_name LowCardinality(String), source_file String,
  source_generation UInt32, publication_revision UInt64
) ENGINE = MergeTree ORDER BY (source_host, source_name, source_file);

-- Published head set: file A at generation 6 (generation 5 has been superseded).
INSERT INTO moraine.v_current_published_source_generations VALUES
  ('h', 'codex', '/a.jsonl', 6, 600);

-- ===================== orphan probe fixture ==============================
-- old = 10 days ago (outside the 24 h horizon); fresh = now.
INSERT INTO moraine.mcp_open_events (event_uid, slot, generation, candidate_generation, session_id, projected_at) VALUES
  ('u1', 0, 100, 100, 'o-collect',      now64(3) - toIntervalDay(10)),
  ('u2', 0, 100, 100, 'o-collect',      now64(3) - toIntervalDay(10)),
  ('u3', 0, 101, 101, 'o-headered',     now64(3) - toIntervalDay(10)),
  ('u4', 0, 102, 102, 'o-fresh',        now64(3)),
  ('u5', 0, 103, 103, 'o-planned',      now64(3) - toIntervalDay(10)),
  ('u6', 0, 104, 104, 'o-planned',      now64(3) - toIntervalDay(10)),
  ('u7', 0, 105, 105, 'o-plandone',     now64(3) - toIntervalDay(10)),
  ('u8', 0, 106, 106, 'o-tombstoned',   now64(3) - toIntervalDay(10));

INSERT INTO moraine.mcp_open_turns (session_id, slot, generation, turn_seq, candidate_generation, projected_at) VALUES
  ('o-collect', 0, 100, 1, 100, now64(3) - toIntervalDay(10)),
  ('o-turnsonly', 0, 107, 1, 107, now64(3) - toIntervalDay(10));

-- 'o-headered' has a header; 'o-tombstoned' has a TOMBSTONE header, which is
-- still a header. Neither is an orphan.
INSERT INTO moraine.mcp_open_publication_headers
  (session_id, candidate_publication_id, slot, generation, dirty_revision, tombstone,
   required_source_heads, required_heads_fingerprint, header_revision, prepared_at) VALUES
  ('o-headered',   'c1', 0, 101, 1, 0, [('h','codex','/a.jsonl',6,600)], 'fp6', 1, now64(3) - toIntervalDay(10)),
  ('o-tombstoned', 'c2', 0, 106, 1, 1, [('h','codex','/a.jsonl',6,600)], 'fp6', 1, now64(3) - toIntervalDay(10));

-- 'o-planned' is preparing generation 103 right now (phase 0 = Planned) while
-- 104 is a crashed earlier prepare. Pair-scoped exclusion protects 103 only.
-- 'o-plandone' has a COMPLETE plan naming 105; a completed plan protects nothing.
INSERT INTO moraine.mcp_open_backfill_plans
  (session_id, candidate_publication_id, slot, candidate_generation, phase, plan_revision) VALUES
  ('o-planned',  'c3', 0, 103, 0, 1),
  ('o-plandone', 'c4', 0, 105, 4, 1),
  ('o-collect',  'c5', 0, 999, 4, 1);

-- ===================== retirement probe fixture ==========================
-- L-RETIRE: one session with a live lineage (fp6, generation 6 published, the
-- pointer, dirty current, prepared 10 days ago) and four older headers:
--   g-stale   -> different fingerprint, stale dirty  => RETIRE
--   g-current -> different fingerprint, CURRENT dirty => keep (a reader can
--                still select it; this is the 162-header case on the host)
--   g-samefp  -> SAME fingerprint as live => keep (within-lineage; the
--                existing reclaimer owns it)
--   g-tomb    -> tombstone, different fingerprint, stale dirty, no children
--                => RETIRE, and it is a childless unit
INSERT INTO moraine.mcp_open_publication_headers
  (session_id, candidate_publication_id, slot, generation, dirty_revision, tombstone,
   required_source_heads, required_heads_fingerprint, header_revision, prepared_at) VALUES
  ('L-RETIRE', 'live',      0, 60, 900, 0, [('h','codex','/a.jsonl',6,600)], 'fp6', 60, now64(3) - toIntervalDay(10)),
  ('L-RETIRE', 'g-stale',   1, 50, 500, 0, [('h','codex','/a.jsonl',5,500)], 'fp5', 50, now64(3) - toIntervalDay(20)),
  ('L-RETIRE', 'g-current', 1, 51, 900, 0, [('h','codex','/a.jsonl',5,500)], 'fp5b',51, now64(3) - toIntervalDay(20)),
  ('L-RETIRE', 'g-samefp',  1, 52, 500, 0, [('h','codex','/a.jsonl',6,600)], 'fp6', 52, now64(3) - toIntervalDay(20)),
  ('L-RETIRE', 'g-tomb',    1, 53, 400, 1, [('h','codex','/a.jsonl',5,500)], 'fp5c',53, now64(3) - toIntervalDay(20));
INSERT INTO moraine.mcp_open_sessions (session_id, slot, generation) VALUES ('L-RETIRE', 0, 60);
INSERT INTO moraine.mcp_open_dirty_sessions (session_id, dirty_revision) VALUES ('L-RETIRE', 900);
INSERT INTO moraine.mcp_open_events (event_uid, slot, generation, candidate_generation, session_id, projected_at) VALUES
  ('r1', 1, 50, 50, 'L-RETIRE', now64(3) - toIntervalDay(20)),
  ('r2', 1, 51, 51, 'L-RETIRE', now64(3) - toIntervalDay(20)),
  ('r3', 1, 52, 52, 'L-RETIRE', now64(3) - toIntervalDay(20)),
  ('r4', 0, 60, 60, 'L-RETIRE', now64(3) - toIntervalDay(10));
INSERT INTO moraine.mcp_open_turns (session_id, slot, generation, turn_seq, candidate_generation, projected_at) VALUES
  ('L-RETIRE', 1, 50, 1, 50, now64(3) - toIntervalDay(20));

-- L-UNPUB: the live head requires generation 5, which is NOT published. P1
-- fails, so nothing in this session retires however stale its other lineages.
INSERT INTO moraine.mcp_open_publication_headers
  (session_id, candidate_publication_id, slot, generation, dirty_revision, tombstone,
   required_source_heads, required_heads_fingerprint, header_revision, prepared_at) VALUES
  ('L-UNPUB', 'live',    0, 70, 900, 0, [('h','codex','/a.jsonl',5,500)], 'fp5', 70, now64(3) - toIntervalDay(10)),
  ('L-UNPUB', 'g-stale', 1, 40, 100, 0, [('h','codex','/a.jsonl',4,400)], 'fp4', 40, now64(3) - toIntervalDay(20));
INSERT INTO moraine.mcp_open_sessions (session_id, slot, generation) VALUES ('L-UNPUB', 0, 70);
INSERT INTO moraine.mcp_open_dirty_sessions (session_id, dirty_revision) VALUES ('L-UNPUB', 900);

-- L-NOPTR: the newest published header is NOT the session pointer (the pointer
-- still names the old lineage), so "published and live" fails. Nothing retires.
INSERT INTO moraine.mcp_open_publication_headers
  (session_id, candidate_publication_id, slot, generation, dirty_revision, tombstone,
   required_source_heads, required_heads_fingerprint, header_revision, prepared_at) VALUES
  ('L-NOPTR', 'newer', 0, 80, 900, 0, [('h','codex','/a.jsonl',6,600)], 'fp6', 80, now64(3) - toIntervalDay(10)),
  ('L-NOPTR', 'older', 1, 41, 100, 0, [('h','codex','/a.jsonl',6,600)], 'fp4', 41, now64(3) - toIntervalDay(20));
INSERT INTO moraine.mcp_open_sessions (session_id, slot, generation) VALUES ('L-NOPTR', 1, 41);
INSERT INTO moraine.mcp_open_dirty_sessions (session_id, dirty_revision) VALUES ('L-NOPTR', 900);

-- L-FRESH: everything retirable except that the live head was prepared one
-- minute ago. The horizon holds it back.
INSERT INTO moraine.mcp_open_publication_headers
  (session_id, candidate_publication_id, slot, generation, dirty_revision, tombstone,
   required_source_heads, required_heads_fingerprint, header_revision, prepared_at) VALUES
  ('L-FRESH', 'live',    0, 90, 900, 0, [('h','codex','/a.jsonl',6,600)], 'fp6', 90, now64(3) - toIntervalMinute(1)),
  ('L-FRESH', 'g-stale', 1, 42, 100, 0, [('h','codex','/a.jsonl',5,500)], 'fp5', 42, now64(3) - toIntervalDay(20));
INSERT INTO moraine.mcp_open_sessions (session_id, slot, generation) VALUES ('L-FRESH', 0, 90);
INSERT INTO moraine.mcp_open_dirty_sessions (session_id, dirty_revision) VALUES ('L-FRESH', 900);

-- L-STALEPTR: the pointer header is published and old, but its dirty revision
-- is stale (the session is mid-reprojection), so it is not what a reader would
-- return. "Published" holds; "and live" does not. Nothing retires.
INSERT INTO moraine.mcp_open_publication_headers
  (session_id, candidate_publication_id, slot, generation, dirty_revision, tombstone,
   required_source_heads, required_heads_fingerprint, header_revision, prepared_at) VALUES
  ('L-STALEPTR', 'ptr',     0, 95, 100, 0, [('h','codex','/a.jsonl',6,600)], 'fp6', 95, now64(3) - toIntervalDay(10)),
  ('L-STALEPTR', 'g-stale', 1, 43,  50, 0, [('h','codex','/a.jsonl',5,500)], 'fp4', 43, now64(3) - toIntervalDay(20));
INSERT INTO moraine.mcp_open_sessions (session_id, slot, generation) VALUES ('L-STALEPTR', 0, 95);
INSERT INTO moraine.mcp_open_dirty_sessions (session_id, dirty_revision) VALUES ('L-STALEPTR', 900);

-- ============ A1B: two headers at ONE generation, and it is the live one ====
--
-- This is the P6 case, and it is why a retirement unit key is no longer
-- "some header at this generation qualifies".
--
-- `mcp_open_publication_headers` is ORDER BY (session_id, candidate_publication_id).
-- `generation` is NOT its primary key, so two publications of one session can
-- occupy one generation and both survive FINAL. The unit key the probe emits
-- is (session_id, generation) and the delete removes EVERY row at that key.
--
-- 'live'  is the pointer target: dirty 900 = dirty(S), fingerprint fpLIVE.
-- 'stale' shares generation 60, sits below the dirty revision, and carries a
--         different (but also currently published) head set, so before P6 it
--         satisfied every row-wise retirement conjunct and emitted key 60.
--
-- Measured 2026-07-28 with the pre-P6 probe: it returned `A1B 60`, and the
-- three shipped deletes left `headers 0, turns 0, events 0` for A1B while
-- mcp_open_sessions still pointed at generation 60 — the live snapshot
-- destroyed and the pointer dangling. With P6 the probe returns nothing for
-- A1B and the survivor census in expected/delete.sql shows it fully intact.
--
-- /b.jsonl@3 exists only so BOTH head sets are currently published. Without it
-- the `unpublished` CTE — which is keyed on (session_id, generation) too —
-- masks the defect by accident rather than by design.
INSERT INTO moraine.v_current_published_source_generations VALUES
  ('h', 'codex', '/b.jsonl', 3, 300);
INSERT INTO moraine.mcp_open_publication_headers
  (session_id, candidate_publication_id, slot, generation, dirty_revision, tombstone,
   required_source_heads, required_heads_fingerprint, header_revision, prepared_at) VALUES
  ('A1B', 'live',  0, 60, 900, 0, [('h','codex','/a.jsonl',6,600)], 'fpLIVE', 100, now64(3) - toIntervalDay(10)),
  ('A1B', 'stale', 0, 60, 500, 0, [('h','codex','/a.jsonl',6,600),('h','codex','/b.jsonl',3,300)], 'fpOLD', 50, now64(3) - toIntervalDay(20));
INSERT INTO moraine.mcp_open_sessions (session_id, slot, generation) VALUES ('A1B', 0, 60);
INSERT INTO moraine.mcp_open_dirty_sessions (session_id, dirty_revision) VALUES ('A1B', 900);
-- The LIVE snapshot's children, written 10 days ago: an old but perfectly live
-- session, so the child horizon does not hold the unit back either.
INSERT INTO moraine.mcp_open_events (event_uid, slot, generation, candidate_generation, session_id, projected_at) VALUES
  ('a1', 0, 60, 60, 'A1B', now64(3) - toIntervalDay(10)),
  ('a2', 0, 60, 60, 'A1B', now64(3) - toIntervalDay(10));
INSERT INTO moraine.mcp_open_turns (session_id, slot, generation, turn_seq, candidate_generation, projected_at) VALUES
  ('A1B', 0, 60, 1, 60, now64(3) - toIntervalDay(10));
