use anyhow::{anyhow, bail, Context, Result};
use moraine_clickhouse::ClickHouseClient;
use moraine_config::{AppConfig, ClickHouseConfig, DEFAULT_BACKEND_NAME};
use moraine_conversations::{
    AnalyticsRange, BackendRepositoryRouter, ClickHouseConversationRepository,
    ConversationRepository, PageRequest, RepoConfig, SessionAnalyticsQuery, SessionLookback,
    TurnListFilter,
};
use reqwest::{Client, Url};
use serde::Deserialize;
use serde_json::{json, Value};
use std::env;
use std::fs;
use std::io::{self, Write};
use std::sync::Arc;
use std::time::{Duration, Instant};
use tokio::sync::oneshot;
use uuid::Uuid;

#[path = "live_clickhouse/support.rs"]
mod support;

use support::{
    Cardinality, MonitorAnalyticsResponse, MonitorResponse, MonitorSessionsResponse,
    SemanticComparison, SemanticObservation,
};

const OWNED_DATABASE_PREFIX: &str = "moraine_test_";
const SANDBOX_CONFIG_PATH: &str = "/sandbox/moraine.toml";
const CLICKHOUSE_URL_ENV: &str = "MORAINE_BENCH_CLICKHOUSE_URL";

#[derive(Debug)]
struct LivePrerequisites {
    clickhouse_url: String,
    clickhouse_username: String,
    clickhouse_password: String,
    sandbox_id: String,
}

impl LivePrerequisites {
    fn load() -> Result<Self> {
        let opt_in = read_required_env("MORAINE_ALLOW_DESTRUCTIVE_TESTS")?;
        let sandbox_id = read_required_env("MORAINE_LIVE_TEST_SANDBOX_ID")?;
        let clickhouse_url = read_required_env(CLICKHOUSE_URL_ENV)?;
        let marker = fs::read_to_string(SANDBOX_CONFIG_PATH).with_context(|| {
            format!("failed to read wrapper-owned sandbox marker {SANDBOX_CONFIG_PATH}")
        })?;
        validate_prerequisites(&opt_in, &sandbox_id, &clickhouse_url, &marker)?;
        Ok(Self {
            clickhouse_url,
            clickhouse_username: read_optional_env("MORAINE_BENCH_CLICKHOUSE_USER", "default")?,
            clickhouse_password: read_optional_env("MORAINE_BENCH_CLICKHOUSE_PASSWORD", "")?,
            sandbox_id,
        })
    }

    fn clickhouse_config(&self, database: &OwnedDatabaseName) -> ClickHouseConfig {
        ClickHouseConfig {
            url: self.clickhouse_url.clone(),
            database: database.as_str().to_string(),
            username: self.clickhouse_username.clone(),
            password: self.clickhouse_password.clone(),
            ..ClickHouseConfig::default()
        }
    }
}

fn read_required_env(name: &str) -> Result<String> {
    match env::var(name) {
        Ok(value) if !value.is_empty() => Ok(value),
        Ok(_) => bail!("{name} must not be empty"),
        Err(env::VarError::NotPresent) => bail!("{name} is required"),
        Err(env::VarError::NotUnicode(_)) => bail!("{name} must contain valid UTF-8"),
    }
}

fn read_optional_env(name: &str, default: &str) -> Result<String> {
    match env::var(name) {
        Ok(value) => Ok(value),
        Err(env::VarError::NotPresent) => Ok(default.to_string()),
        Err(env::VarError::NotUnicode(_)) => bail!("{name} must contain valid UTF-8"),
    }
}

fn validate_prerequisites(
    opt_in: &str,
    sandbox_id: &str,
    clickhouse_url: &str,
    sandbox_config: &str,
) -> Result<()> {
    if opt_in != "1" {
        bail!("MORAINE_ALLOW_DESTRUCTIVE_TESTS must equal 1");
    }
    if !valid_sandbox_id(sandbox_id) {
        bail!("MORAINE_LIVE_TEST_SANDBOX_ID must match sb-[a-f0-9]{{6}}, got {sandbox_id:?}");
    }
    let url = Url::parse(clickhouse_url)
        .with_context(|| format!("{CLICKHOUSE_URL_ENV} is not a valid URL"))?;
    if url.scheme() != "http"
        || url.host_str() != Some("clickhouse")
        || url.port_or_known_default() != Some(8123)
        || url.path() != "/"
        || url.query().is_some()
        || url.fragment().is_some()
        || !url.username().is_empty()
        || url.password().is_some()
    {
        bail!(
            "{CLICKHOUSE_URL_ENV} must be the credential-free wrapper-owned endpoint http://clickhouse:8123"
        );
    }
    let expected_marker =
        format!("# Generated by scripts/dev/sandbox/moraine-sandbox for {sandbox_id}");
    if sandbox_config.lines().next() != Some(expected_marker.as_str()) {
        bail!("sandbox config marker does not own {sandbox_id}");
    }
    if !sandbox_config
        .lines()
        .any(|line| line.trim() == "url = \"http://clickhouse:8123\"")
    {
        bail!("sandbox config does not identify the wrapper-owned ClickHouse endpoint");
    }
    Ok(())
}

fn valid_sandbox_id(value: &str) -> bool {
    value.len() == 9
        && value.starts_with("sb-")
        && value[3..]
            .bytes()
            .all(|byte| byte.is_ascii_digit() || (b'a'..=b'f').contains(&byte))
}

#[derive(Clone, Debug, PartialEq, Eq)]
struct OwnedDatabaseName(String);

impl OwnedDatabaseName {
    fn generate() -> Self {
        let database = Self(format!(
            "{OWNED_DATABASE_PREFIX}{}",
            Uuid::new_v4().simple()
        ));
        debug_assert!(validate_owned_database_name(database.as_str()).is_ok());
        database
    }

    fn as_str(&self) -> &str {
        &self.0
    }
}

fn validate_owned_database_name(value: &str) -> Result<()> {
    if value.is_empty() || value == "moraine" {
        bail!("refusing unsafe live-test database name {value:?}");
    }
    let suffix = value
        .strip_prefix(OWNED_DATABASE_PREFIX)
        .context("live-test database must use the moraine_test_<uuid> prefix")?;
    if suffix.len() != 32
        || !suffix
            .bytes()
            .all(|byte| byte.is_ascii_digit() || (b'a'..=b'f').contains(&byte))
    {
        bail!("live-test database suffix must be 32 lowercase ASCII hexadecimal digits");
    }
    if !value
        .bytes()
        .all(|byte| byte.is_ascii_alphanumeric() || byte == b'_')
    {
        bail!("live-test database must contain only ASCII letters, digits, and underscore");
    }
    Ok(())
}

fn cleanup_statement(database: &OwnedDatabaseName) -> String {
    format!("DROP DATABASE IF EXISTS `{}` SYNC", database.as_str())
}

fn write_pre_mutation_diagnostic(
    output: &mut impl Write,
    database: &OwnedDatabaseName,
    sandbox_id: &str,
) -> Result<()> {
    writeln!(output, "live ClickHouse database: {}", database.as_str())
        .context("failed to emit owned live database identity")?;
    writeln!(
        output,
        "cleanup: sandbox={} endpoint=<redacted-owned-clickhouse> query={}",
        sandbox_id,
        cleanup_statement(database)
    )
    .context("failed to emit owned live database cleanup diagnostic")?;
    Ok(())
}

fn prepare_owned_database_identity_with_writer(
    sandbox_id: &str,
    output: &mut impl Write,
) -> Result<OwnedDatabaseName> {
    let database = OwnedDatabaseName::generate();
    validate_owned_database_name(database.as_str())?;
    write_pre_mutation_diagnostic(output, &database, sandbox_id)?;
    Ok(database)
}

fn prepare_owned_database_identity(sandbox_id: &str) -> Result<OwnedDatabaseName> {
    prepare_owned_database_identity_with_writer(sandbox_id, &mut io::stderr().lock())
}

async fn cleanup_database(
    clickhouse: &ClickHouseClient,
    database: &OwnedDatabaseName,
) -> Result<()> {
    clickhouse
        .request_text(
            &cleanup_statement(database),
            None,
            Some("system"),
            false,
            None,
        )
        .await
        .with_context(|| format!("failed to remove owned database {}", database.as_str()))?;
    Ok(())
}

#[derive(Deserialize)]
struct DatabaseNameRow {
    name: String,
}

async fn owned_database_census(clickhouse: &ClickHouseClient) -> Result<Vec<String>> {
    let rows: Vec<DatabaseNameRow> = clickhouse
        .query_rows(
            "SELECT name FROM system.databases \
             WHERE startsWith(name, 'moraine_test_') \
             ORDER BY name FORMAT JSONEachRow",
            Some("system"),
        )
        .await
        .context("failed to census owned live-test databases")?;
    Ok(rows.into_iter().map(|row| row.name).collect())
}

async fn assert_owned_database_census_empty(
    clickhouse: &ClickHouseClient,
    phase: &str,
) -> Result<()> {
    let databases = owned_database_census(clickhouse).await?;
    if !databases.is_empty() {
        bail!(
            "{phase} owned-resource census expected zero {OWNED_DATABASE_PREFIX}* databases, found {databases:?}"
        );
    }
    Ok(())
}

fn finish_with_cleanup(outcome: Result<()>, cleanup: Result<()>) -> Result<()> {
    match (outcome, cleanup) {
        (Ok(()), Ok(())) => Ok(()),
        (Err(error), Ok(())) => Err(error),
        (Ok(()), Err(cleanup_error)) => {
            Err(cleanup_error.context("live ClickHouse teardown failed"))
        }
        (Err(error), Err(cleanup_error)) => Err(anyhow!(
            "{error:#}; live ClickHouse teardown also failed: {cleanup_error:#}"
        )),
    }
}

fn live_client(
    prerequisites: &LivePrerequisites,
    database: &OwnedDatabaseName,
) -> Result<ClickHouseClient> {
    ClickHouseClient::new(prerequisites.clickhouse_config(database))
        .context("failed to construct owned live ClickHouse client")
}

async fn install_schema_fixture(
    clickhouse: &ClickHouseClient,
    database: &OwnedDatabaseName,
) -> Result<()> {
    let database = database.as_str();
    let insert = format!(
        r#"INSERT INTO `{database}`.`events`
(
  ingested_at, event_uid, session_id, session_date, source_name, harness, source_file,
  source_ref, record_ts, event_ts, event_kind, actor_kind, payload_type, op_kind, request_id,
  trace_id, turn_index, model, input_tokens, output_tokens, text_content, payload_json,
  event_version
)
VALUES
(
  addMonths(now64(3), -1), 'issue454-dedup', 'issue454-dedup-session', today(),
  'fixture', 'codex', 'fixture-dedup', 'fixture-old', '2026-01-02T03:04:04.500Z',
  toStartOfMinute(now64(3)), 'message', 'assistant', 'text', '', 'issue454-request', 'issue454-trace',
  1, 'old-model', 11, 0, 'old', '{{}}', 1
),
(
  now64(3), 'issue454-dedup', 'issue454-dedup-session', today(), 'fixture', 'codex',
  'fixture-dedup', 'fixture-new', '2026-01-02T03:04:05.678Z', toStartOfMinute(now64(3)), 'message',
  'assistant', 'text', '', 'issue454-request', 'issue454-trace', 1, 'new-model',
  13, 0, 'new', '{{}}', 2
),
(
  now64(3), 'issue454-web-a', 'issue454-web-session', today(), 'fixture', 'codex',
  'fixture-web', 'issue454-web-a', '2026-01-02T03:05:00.000Z', now64(3),
  'tool_call', 'assistant', 'web_search_call', 'search', '', 'issue454-trace', 1,
  '', 0, 0, '', '{{"action":{{"query":"a"}}}}', 1
),
(
  now64(3), 'issue454-web-z', 'issue454-web-session', today(), 'fixture', 'codex',
  'fixture-web', 'issue454-web-z', '2026-01-02T03:05:00.000Z', now64(3),
  'tool_call', 'assistant', 'web_search_call', 'search', '', 'issue454-trace', 1,
  '', 0, 0, '', '{{"action":{{"query":"z"}}}}', 1
)"#
    );
    clickhouse
        .request_text(&insert, None, Some(database), false, None)
        .await
        .context("failed to insert live-schema fixtures")?;
    Ok(())
}

#[tokio::test]
#[ignore = "requires wrapper-owned live ClickHouse and destructive opt-in"]
async fn live_schema_semantics_and_teardown() -> Result<()> {
    let prerequisites = LivePrerequisites::load()?;
    let database = prepare_owned_database_identity(&prerequisites.sandbox_id)?;
    let clickhouse = live_client(&prerequisites, &database)?;
    assert_owned_database_census_empty(&clickhouse, "before mutation").await?;

    let outcome = async {
        clickhouse
            .run_migrations()
            .await
            .context("failed to migrate temporary live-schema database")?;
        let repository =
            ClickHouseConversationRepository::new(clickhouse.clone(), RepoConfig::default());

        let empty = repository
            .analytics_series(AnalyticsRange::FifteenMinutes)
            .await
            .context("empty-window analytics read failed")?;
        assert!(empty.tokens.is_empty());
        assert!(empty.turns.is_empty());
        assert!(empty.concurrent_sessions.is_empty());
        let empty_heartbeat = repository
            .latest_ingest_heartbeat()
            .await
            .context("empty heartbeat read failed")?;
        assert!(empty_heartbeat.table_present);
        assert!(empty_heartbeat.latest.is_none());

        clickhouse
            .request_text(
                &format!(
                    "ALTER TABLE `{}`.`ingest_heartbeats` DROP COLUMN IF EXISTS backend_sinks",
                    database.as_str()
                ),
                None,
                Some(database.as_str()),
                false,
                None,
            )
            .await
            .context("failed to remove optional heartbeat column")?;
        let legacy_repository =
            ClickHouseConversationRepository::new(clickhouse.clone(), RepoConfig::default());
        let legacy_heartbeat = legacy_repository
            .latest_ingest_heartbeat()
            .await
            .context("legacy heartbeat read failed")?;
        assert!(legacy_heartbeat.table_present);
        assert!(legacy_heartbeat.latest.is_none());

        install_schema_fixture(&clickhouse, &database).await?;

        #[derive(Deserialize)]
        struct TurnTimestampTypeRow {
            started_at_type: String,
            ended_at_type: String,
        }
        let turn_timestamp_types: Vec<TurnTimestampTypeRow> = clickhouse
            .query_rows(
                &format!(
                    "SELECT toTypeName(started_at) AS started_at_type, \
                     toTypeName(ended_at) AS ended_at_type \
                     FROM `{}`.`v_turn_summary` \
                     WHERE session_id = 'issue454-dedup-session' \
                     FORMAT JSONEachRow",
                    database.as_str()
                ),
                Some(database.as_str()),
            )
            .await
            .context("turn summary timestamp type query failed")?;
        assert_eq!(turn_timestamp_types.len(), 1);
        assert!(
            turn_timestamp_types[0]
                .started_at_type
                .starts_with("DateTime64(3"),
            "started_at must remain typed: {}",
            turn_timestamp_types[0].started_at_type
        );
        assert!(
            turn_timestamp_types[0]
                .ended_at_type
                .starts_with("DateTime64(3"),
            "ended_at must remain typed: {}",
            turn_timestamp_types[0].ended_at_type
        );

        #[derive(Deserialize)]
        struct ModelRow {
            model: String,
        }
        let canonical: Vec<ModelRow> = clickhouse
            .query_rows(
                &format!(
                    "SELECT model FROM (SELECT * FROM `{}`.`events` FINAL \
                     SETTINGS do_not_merge_across_partitions_select_final = 0) \
                     WHERE event_uid = 'issue454-dedup' FORMAT JSONEachRow",
                    database.as_str()
                ),
                Some(database.as_str()),
            )
            .await
            .context("canonical cross-partition fixture query failed")?;
        assert_eq!(canonical.len(), 1);
        assert_eq!(canonical[0].model, "new-model");
        let stale_predicate: Vec<ModelRow> = clickhouse
            .query_rows(
                &format!(
                    "SELECT model FROM (SELECT * FROM `{}`.`events` FINAL \
                     SETTINGS do_not_merge_across_partitions_select_final = 0) \
                     WHERE event_uid = 'issue454-dedup' AND model = 'old-model' \
                     FORMAT JSONEachRow",
                    database.as_str()
                ),
                Some(database.as_str()),
            )
            .await
            .context("canonical outer-predicate query failed")?;
        assert!(stale_predicate.is_empty());

        let populated_repository =
            ClickHouseConversationRepository::new(clickhouse.clone(), RepoConfig::default());
        let analytics = populated_repository
            .analytics_series(AnalyticsRange::FifteenMinutes)
            .await
            .context("populated analytics read failed")?;
        assert!(analytics
            .tokens
            .iter()
            .any(|point| point.model == "new-model"));
        assert!(!analytics
            .tokens
            .iter()
            .any(|point| point.model == "old-model"));
        let sessions = populated_repository
            .list_session_analytics(SessionAnalyticsQuery {
                lookback: SessionLookback::All,
                limit: 50,
            })
            .await
            .context("populated session analytics read failed")?;
        let deduped = sessions
            .iter()
            .find(|session| session.summary.session_id == "issue454-dedup-session")
            .context("deduped fixture session missing")?;
        assert_eq!(deduped.summary.total_events, 1);
        assert_eq!(deduped.models, vec!["new-model"]);
        const FIXTURE_EVENT_UNIX_MS: i64 = 1_767_323_045_678;
        assert_eq!(deduped.summary.first_event_unix_ms, FIXTURE_EVENT_UNIX_MS);
        assert_eq!(deduped.summary.last_event_unix_ms, FIXTURE_EVENT_UNIX_MS);

        let listed_turns = populated_repository
            .list_turns(
                "issue454-dedup-session",
                TurnListFilter::default(),
                PageRequest::default(),
            )
            .await
            .context("typed turn list projection failed")?;
        assert_eq!(listed_turns.items.len(), 1);
        assert_eq!(
            listed_turns.items[0].started_at_unix_ms,
            FIXTURE_EVENT_UNIX_MS
        );
        assert_eq!(
            listed_turns.items[0].ended_at_unix_ms,
            FIXTURE_EVENT_UNIX_MS
        );

        let mcp_session = populated_repository
            .get_mcp_session("issue454-dedup-session")
            .await
            .context("typed MCP session projection failed")?
            .context("MCP fixture session missing")?;
        assert_eq!(mcp_session.turns.len(), 1);
        assert_eq!(
            mcp_session.turns[0].metadata.started_at_unix_ms,
            FIXTURE_EVENT_UNIX_MS
        );
        let turn = populated_repository
            .get_turn("issue454-dedup-session", 1)
            .await
            .context("view-only turn read failed")?
            .context("view-only fixture turn missing")?;
        assert_eq!(turn.summary.total_events, 1);
        assert_eq!(turn.summary.started_at_unix_ms, FIXTURE_EVENT_UNIX_MS);
        assert_eq!(turn.summary.ended_at_unix_ms, FIXTURE_EVENT_UNIX_MS);
        assert_eq!(turn.events.len(), 1);
        assert_eq!(turn.events[0].text_content, "new");
        let web = populated_repository
            .list_web_searches(1000)
            .await
            .context("same-millisecond web feed read failed")?;
        let fixture_refs = web
            .iter()
            .filter(|event| event.session_id == "issue454-web-session")
            .map(|event| event.source_ref.as_str())
            .collect::<Vec<_>>();
        assert_eq!(fixture_refs, vec!["issue454-web-z", "issue454-web-a"]);
        Ok(())
    }
    .await;

    let cleanup = cleanup_database(&clickhouse, &database).await;
    let census = assert_owned_database_census_empty(&clickhouse, "after cleanup").await;
    finish_with_cleanup(outcome, finish_with_cleanup(cleanup, census))
}

fn direct_analytics_semantics(
    snapshot: moraine_conversations::AnalyticsSnapshot,
) -> Result<SemanticObservation> {
    let payload = json!({
        "tokens": snapshot.tokens,
        "turns": snapshot.turns,
        "concurrent_sessions": snapshot.concurrent_sessions,
    });
    SemanticObservation::new(
        Cardinality::AnalyticsSeries {
            tokens: payload["tokens"].as_array().map_or(0, Vec::len),
            turns: payload["turns"].as_array().map_or(0, Vec::len),
            concurrent_sessions: payload["concurrent_sessions"]
                .as_array()
                .map_or(0, Vec::len),
        },
        &payload,
    )
}

fn direct_sessions_semantics(
    sessions: &[moraine_conversations::SessionAnalytics],
) -> Result<SemanticObservation> {
    let payload = Value::Array(
        sessions
            .iter()
            .map(|session| {
                json!({
                    "session_id": session.summary.session_id,
                    "harness": session.harness,
                    "started_at_unix_ms": session.summary.first_event_unix_ms,
                    "ended_at_unix_ms": session.summary.last_event_unix_ms,
                    "models": session.models,
                    "trace_id": session.trace_id,
                    "turns": session.turns.len(),
                    "tool_calls": session.summary.tool_calls,
                })
            })
            .collect(),
    );
    SemanticObservation::new(
        Cardinality::Sessions {
            sessions: sessions.len(),
        },
        &payload,
    )
}

async fn monitor_semantics<T: MonitorResponse>(
    client: &Client,
    url: &Url,
) -> Result<SemanticObservation> {
    let response = client
        .get(url.clone())
        .send()
        .await
        .with_context(|| format!("monitor request failed: {url}"))?;
    let status = response.status();
    let body = response.bytes().await.context("monitor body read failed")?;
    if !status.is_success() {
        bail!(
            "monitor returned HTTP {status}: {}",
            String::from_utf8_lossy(&body)
        );
    }
    serde_json::from_slice::<T>(&body)
        .context("monitor returned invalid JSON")?
        .into_semantics()
}

async fn start_owned_monitor(
    repository: ClickHouseConversationRepository,
) -> Result<(
    Url,
    oneshot::Sender<()>,
    tokio::task::JoinHandle<Result<()>>,
    std::path::PathBuf,
)> {
    let listener = tokio::net::TcpListener::bind("127.0.0.1:0")
        .await
        .context("failed to bind monitor listener")?;
    let port = listener.local_addr()?.port();

    let base = Url::parse(&format!("http://127.0.0.1:{port}/api/v1/"))?;
    let health_url = base.join("health")?;
    let client = Client::builder().timeout(Duration::from_secs(5)).build()?;
    let injected: Arc<dyn ConversationRepository> = Arc::new(repository);
    let router = Arc::new(BackendRepositoryRouter::from_preloaded_for_testing(
        Arc::new(AppConfig::default()),
        [(DEFAULT_BACKEND_NAME.to_string(), injected)],
    )?);

    let static_dir =
        env::temp_dir().join(format!("moraine-live-monitor-{}", Uuid::new_v4().simple()));
    fs::create_dir(&static_dir).context("failed to create monitor static directory")?;
    if let Err(error) = fs::write(static_dir.join("index.html"), "<!doctype html>") {
        let _ = fs::remove_dir_all(&static_dir);
        return Err(error).context("failed to create monitor static index");
    }

    let (shutdown_tx, shutdown_rx) = oneshot::channel();
    let server_static_dir = static_dir.clone();
    let server = tokio::spawn(async move {
        moraine_monitor_core::run_server_with_listener(
            router,
            listener,
            server_static_dir,
            async move {
                let _ = shutdown_rx.await;
            },
        )
        .await
    });
    let deadline = Instant::now() + Duration::from_secs(5);
    loop {
        match client.get(health_url.clone()).send().await {
            Ok(response) if response.status().is_success() => break,
            _ if Instant::now() < deadline => tokio::time::sleep(Duration::from_millis(20)).await,
            _ => {
                let _ = shutdown_tx.send(());
                let _ = server.await;
                let _ = fs::remove_dir_all(&static_dir);
                bail!("owned monitor did not become ready before timeout");
            }
        }
    }
    Ok((base, shutdown_tx, server, static_dir))
}

#[tokio::test]
#[ignore = "requires wrapper-owned live ClickHouse and destructive opt-in"]
async fn live_monitor_repository_semantic_parity() -> Result<()> {
    let prerequisites = LivePrerequisites::load()?;
    let database = prepare_owned_database_identity(&prerequisites.sandbox_id)?;
    let clickhouse = live_client(&prerequisites, &database)?;
    assert_owned_database_census_empty(&clickhouse, "before mutation").await?;

    let outcome = async {
        clickhouse
            .run_migrations()
            .await
            .context("failed to migrate parity database")?;
        install_schema_fixture(&clickhouse, &database).await?;

        let monitor_repository =
            ClickHouseConversationRepository::new(clickhouse.clone(), RepoConfig::default());
        let direct_repository =
            ClickHouseConversationRepository::new(clickhouse.clone(), RepoConfig::default());
        let client = Client::builder().timeout(Duration::from_secs(30)).build()?;
        let (base, shutdown, server, static_dir) = start_owned_monitor(monitor_repository).await?;

        let parity = async {
            let monitor_analytics = monitor_semantics::<MonitorAnalyticsResponse>(
                &client,
                &base.join("analytics?range=24h")?,
            )
            .await?;
            let direct_analytics = direct_analytics_semantics(
                direct_repository
                    .analytics_series(AnalyticsRange::TwentyFourHours)
                    .await?,
            )?;
            let analytics_comparison =
                SemanticComparison::compare(&monitor_analytics, &direct_analytics);
            if !analytics_comparison.passed() {
                bail!("monitor/repository analytics semantic mismatch: {analytics_comparison:?}");
            }

            let monitor_sessions = monitor_semantics::<MonitorSessionsResponse>(
                &client,
                &base.join("sessions?since=30d&limit=50")?,
            )
            .await?;
            let direct_sessions = direct_sessions_semantics(
                &direct_repository
                    .list_session_analytics(SessionAnalyticsQuery {
                        lookback: SessionLookback::ThirtyDays,
                        limit: 50,
                    })
                    .await?,
            )?;
            let sessions_comparison =
                SemanticComparison::compare(&monitor_sessions, &direct_sessions);
            if !sessions_comparison.passed() {
                bail!("monitor/repository sessions semantic mismatch: {sessions_comparison:?}");
            }
            Ok(())
        }
        .await;

        let _ = shutdown.send(());
        let server_result = match server.await {
            Ok(result) => result,
            Err(error) => Err(anyhow!("owned monitor task failed to join: {error}")),
        };
        let static_cleanup = fs::remove_dir_all(&static_dir)
            .context("failed to remove owned monitor static directory");
        let monitor_cleanup = finish_with_cleanup(server_result, static_cleanup);
        finish_with_cleanup(parity, monitor_cleanup)
    }
    .await;

    let cleanup = cleanup_database(&clickhouse, &database).await;
    let census = assert_owned_database_census_empty(&clickhouse, "after cleanup").await;
    finish_with_cleanup(outcome, finish_with_cleanup(cleanup, census))
}

#[cfg(test)]
mod tests {
    use super::*;

    const MARKER: &str = "# Generated by scripts/dev/sandbox/moraine-sandbox for sb-a1b2c3\n[clickhouse]\nurl = \"http://clickhouse:8123\"\ndatabase = \"moraine\"\n";

    #[test]
    fn destructive_prerequisites_fail_closed_before_sql() {
        assert!(validate_prerequisites("", "sb-a1b2c3", "http://clickhouse:8123", MARKER).is_err());
        assert!(
            validate_prerequisites("1", "sb-zzzzzz", "http://clickhouse:8123", MARKER).is_err()
        );
        assert!(validate_prerequisites("1", "sb-a1b2c3", "http://127.0.0.1:8123", MARKER).is_err());
        assert!(validate_prerequisites(
            "1",
            "sb-a1b2c3",
            "http://user:secret@clickhouse:8123",
            MARKER
        )
        .is_err());
        assert!(
            validate_prerequisites("1", "sb-a1b2c3", "http://clickhouse:8123", "wrong marker")
                .is_err()
        );
        validate_prerequisites("1", "sb-a1b2c3", "http://clickhouse:8123", MARKER).unwrap();
    }

    #[test]
    fn concurrent_live_bodies_generate_distinct_internal_database_identities() {
        use std::sync::Barrier;
        use std::thread;

        let start = Arc::new(Barrier::new(3));
        let handles = ["sb-a1b2c3", "sb-d4e5f6"].map(|sandbox_id| {
            let start = Arc::clone(&start);
            thread::spawn(move || {
                let mut diagnostic = Vec::new();
                start.wait();
                let database =
                    prepare_owned_database_identity_with_writer(sandbox_id, &mut diagnostic)
                        .unwrap();
                (sandbox_id, database, String::from_utf8(diagnostic).unwrap())
            })
        });
        start.wait();
        let [(first_sandbox, first, first_diagnostic), (second_sandbox, second, second_diagnostic)] =
            handles.map(|handle| handle.join().unwrap());

        assert_ne!(first, second);
        for (sandbox_id, database, diagnostic) in [
            (first_sandbox, first, first_diagnostic),
            (second_sandbox, second, second_diagnostic),
        ] {
            validate_owned_database_name(database.as_str()).unwrap();
            assert_eq!(database.as_str().len(), OWNED_DATABASE_PREFIX.len() + 32);
            assert!(diagnostic.starts_with(&format!(
                "live ClickHouse database: {}\n",
                database.as_str()
            )));
            assert!(diagnostic.contains(&format!("cleanup: sandbox={sandbox_id} ")));
            assert!(diagnostic.contains(&cleanup_statement(&database)));
        }

        for unsafe_name in [
            "",
            "moraine",
            "moraine_test_",
            "moraine_test_xyz",
            "moraine_test_ABCDEF0123456789abcdef0123456789",
            "other_0123456789abcdef0123456789abcdef",
            "moraine_test_0123456789abcdef0123456789abcde;DROP",
        ] {
            assert!(
                validate_owned_database_name(unsafe_name).is_err(),
                "accepted {unsafe_name:?}"
            );
        }
    }

    #[test]
    fn cleanup_statement_can_only_be_built_from_validated_owned_name() {
        let database = OwnedDatabaseName::generate();
        assert_eq!(
            cleanup_statement(&database),
            format!("DROP DATABASE IF EXISTS `{}` SYNC", database.as_str())
        );
    }

    #[test]
    fn cleanup_composition_preserves_original_and_cleanup_errors() {
        let original = finish_with_cleanup(Err(anyhow!("query failed")), Ok(()))
            .unwrap_err()
            .to_string();
        assert_eq!(original, "query failed");
        let cleanup = finish_with_cleanup(Ok(()), Err(anyhow!("drop failed")))
            .unwrap_err()
            .to_string();
        assert!(cleanup.contains("live ClickHouse teardown failed"));
        let both = finish_with_cleanup(
            Err(anyhow!("assertion failed")),
            Err(anyhow!("drop failed")),
        )
        .unwrap_err()
        .to_string();
        assert!(both.contains("assertion failed"));
        assert!(both.contains("drop failed"));
    }
}
