use anyhow::{anyhow, bail, Context, Result};
use moraine_clickhouse::ClickHouseClient;
use moraine_config::{AppConfig, ClickHouseConfig, DEFAULT_BACKEND_NAME};
use moraine_conversations::{
    with_repository_query_id, AnalyticsRange, BackendRepositoryRouter,
    ClickHouseConversationRepository, ConversationListSort, ConversationRepository,
    McpSessionListFilter, PageRequest, RepoConfig, SearchEventsQuery, SearchStrategyHint,
    SessionAnalyticsQuery, SessionLookback, TurnListFilter,
};
use reqwest::{Client, Url};
use serde::{Deserialize, Serialize};
use serde_json::{json, Value};
use std::collections::HashMap;
use std::env;
use std::fs;
use std::io::{self, Write};
use std::sync::Arc;
use std::time::{Duration, Instant};
use tokio::sync::oneshot;
use uuid::Uuid;

#[path = "live_clickhouse/support.rs"]
mod support;

use support::{
    Cardinality, MonitorAnalyticsResponse, MonitorResponse, MonitorSessionsResponse,
    SemanticComparison, SemanticObservation,
};

const OWNED_DATABASE_PREFIX: &str = "moraine_test_";
const SANDBOX_CONFIG_PATH: &str = "/sandbox/moraine.toml";
const CLICKHOUSE_URL_ENV: &str = "MORAINE_BENCH_CLICKHOUSE_URL";

#[derive(Debug)]
struct LivePrerequisites {
    clickhouse_url: String,
    clickhouse_username: String,
    clickhouse_password: String,
    sandbox_id: String,
}

impl LivePrerequisites {
    fn load() -> Result<Self> {
        let opt_in = read_required_env("MORAINE_ALLOW_DESTRUCTIVE_TESTS")?;
        let sandbox_id = read_required_env("MORAINE_LIVE_TEST_SANDBOX_ID")?;
        let clickhouse_url = read_required_env(CLICKHOUSE_URL_ENV)?;
        let marker = fs::read_to_string(SANDBOX_CONFIG_PATH).with_context(|| {
            format!("failed to read wrapper-owned sandbox marker {SANDBOX_CONFIG_PATH}")
        })?;
        validate_prerequisites(&opt_in, &sandbox_id, &clickhouse_url, &marker)?;
        Ok(Self {
            clickhouse_url,
            clickhouse_username: read_optional_env("MORAINE_BENCH_CLICKHOUSE_USER", "default")?,
            clickhouse_password: read_optional_env("MORAINE_BENCH_CLICKHOUSE_PASSWORD", "")?,
            sandbox_id,
        })
    }

    fn clickhouse_config(&self, database: &OwnedDatabaseName) -> ClickHouseConfig {
        ClickHouseConfig {
            url: self.clickhouse_url.clone(),
            database: database.as_str().to_string(),
            username: self.clickhouse_username.clone(),
            password: self.clickhouse_password.clone(),
            ..ClickHouseConfig::default()
        }
    }
}

fn read_required_env(name: &str) -> Result<String> {
    match env::var(name) {
        Ok(value) if !value.is_empty() => Ok(value),
        Ok(_) => bail!("{name} must not be empty"),
        Err(env::VarError::NotPresent) => bail!("{name} is required"),
        Err(env::VarError::NotUnicode(_)) => bail!("{name} must contain valid UTF-8"),
    }
}

fn read_optional_env(name: &str, default: &str) -> Result<String> {
    match env::var(name) {
        Ok(value) => Ok(value),
        Err(env::VarError::NotPresent) => Ok(default.to_string()),
        Err(env::VarError::NotUnicode(_)) => bail!("{name} must contain valid UTF-8"),
    }
}

fn validate_prerequisites(
    opt_in: &str,
    sandbox_id: &str,
    clickhouse_url: &str,
    sandbox_config: &str,
) -> Result<()> {
    if opt_in != "1" {
        bail!("MORAINE_ALLOW_DESTRUCTIVE_TESTS must equal 1");
    }
    if !valid_sandbox_id(sandbox_id) {
        bail!("MORAINE_LIVE_TEST_SANDBOX_ID must match sb-[a-f0-9]{{6}}, got {sandbox_id:?}");
    }
    let url = Url::parse(clickhouse_url)
        .with_context(|| format!("{CLICKHOUSE_URL_ENV} is not a valid URL"))?;
    if url.scheme() != "http"
        || url.host_str() != Some("clickhouse")
        || url.port_or_known_default() != Some(8123)
        || url.path() != "/"
        || url.query().is_some()
        || url.fragment().is_some()
        || !url.username().is_empty()
        || url.password().is_some()
    {
        bail!(
            "{CLICKHOUSE_URL_ENV} must be the credential-free wrapper-owned endpoint http://clickhouse:8123"
        );
    }
    let expected_marker =
        format!("# Generated by scripts/dev/sandbox/moraine-sandbox for {sandbox_id}");
    if sandbox_config.lines().next() != Some(expected_marker.as_str()) {
        bail!("sandbox config marker does not own {sandbox_id}");
    }
    if !sandbox_config
        .lines()
        .any(|line| line.trim() == "url = \"http://clickhouse:8123\"")
    {
        bail!("sandbox config does not identify the wrapper-owned ClickHouse endpoint");
    }
    Ok(())
}

fn valid_sandbox_id(value: &str) -> bool {
    value.len() == 9
        && value.starts_with("sb-")
        && value[3..]
            .bytes()
            .all(|byte| byte.is_ascii_digit() || (b'a'..=b'f').contains(&byte))
}

#[derive(Clone, Debug, PartialEq, Eq)]
struct OwnedDatabaseName(String);

impl OwnedDatabaseName {
    fn generate() -> Self {
        let database = Self(format!(
            "{OWNED_DATABASE_PREFIX}{}",
            Uuid::new_v4().simple()
        ));
        debug_assert!(validate_owned_database_name(database.as_str()).is_ok());
        database
    }

    fn as_str(&self) -> &str {
        &self.0
    }
}

fn validate_owned_database_name(value: &str) -> Result<()> {
    if value.is_empty() || value == "moraine" {
        bail!("refusing unsafe live-test database name {value:?}");
    }
    let suffix = value
        .strip_prefix(OWNED_DATABASE_PREFIX)
        .context("live-test database must use the moraine_test_<uuid> prefix")?;
    if suffix.len() != 32
        || !suffix
            .bytes()
            .all(|byte| byte.is_ascii_digit() || (b'a'..=b'f').contains(&byte))
    {
        bail!("live-test database suffix must be 32 lowercase ASCII hexadecimal digits");
    }
    if !value
        .bytes()
        .all(|byte| byte.is_ascii_alphanumeric() || byte == b'_')
    {
        bail!("live-test database must contain only ASCII letters, digits, and underscore");
    }
    Ok(())
}

fn cleanup_statement(database: &OwnedDatabaseName) -> String {
    format!("DROP DATABASE IF EXISTS `{}` SYNC", database.as_str())
}

fn write_pre_mutation_diagnostic(
    output: &mut impl Write,
    database: &OwnedDatabaseName,
    sandbox_id: &str,
) -> Result<()> {
    writeln!(output, "live ClickHouse database: {}", database.as_str())
        .context("failed to emit owned live database identity")?;
    writeln!(
        output,
        "cleanup: sandbox={} endpoint=<redacted-owned-clickhouse> query={}",
        sandbox_id,
        cleanup_statement(database)
    )
    .context("failed to emit owned live database cleanup diagnostic")?;
    Ok(())
}

fn prepare_owned_database_identity_with_writer(
    sandbox_id: &str,
    output: &mut impl Write,
) -> Result<OwnedDatabaseName> {
    let database = OwnedDatabaseName::generate();
    validate_owned_database_name(database.as_str())?;
    write_pre_mutation_diagnostic(output, &database, sandbox_id)?;
    Ok(database)
}

fn prepare_owned_database_identity(sandbox_id: &str) -> Result<OwnedDatabaseName> {
    prepare_owned_database_identity_with_writer(sandbox_id, &mut io::stderr().lock())
}

async fn cleanup_database(
    clickhouse: &ClickHouseClient,
    database: &OwnedDatabaseName,
) -> Result<()> {
    clickhouse
        .request_text(
            &cleanup_statement(database),
            None,
            Some("system"),
            false,
            None,
        )
        .await
        .with_context(|| format!("failed to remove owned database {}", database.as_str()))?;
    Ok(())
}

#[derive(Deserialize)]
struct DatabaseNameRow {
    name: String,
}

async fn owned_database_census(clickhouse: &ClickHouseClient) -> Result<Vec<String>> {
    let rows: Vec<DatabaseNameRow> = clickhouse
        .query_rows(
            "SELECT name FROM system.databases \
             WHERE startsWith(name, 'moraine_test_') \
             ORDER BY name FORMAT JSONEachRow",
            Some("system"),
        )
        .await
        .context("failed to census owned live-test databases")?;
    Ok(rows.into_iter().map(|row| row.name).collect())
}

async fn assert_owned_database_census_empty(
    clickhouse: &ClickHouseClient,
    phase: &str,
) -> Result<()> {
    let databases = owned_database_census(clickhouse).await?;
    if !databases.is_empty() {
        bail!(
            "{phase} owned-resource census expected zero {OWNED_DATABASE_PREFIX}* databases, found {databases:?}"
        );
    }
    Ok(())
}

fn finish_with_cleanup(outcome: Result<()>, cleanup: Result<()>) -> Result<()> {
    match (outcome, cleanup) {
        (Ok(()), Ok(())) => Ok(()),
        (Err(error), Ok(())) => Err(error),
        (Ok(()), Err(cleanup_error)) => {
            Err(cleanup_error.context("live ClickHouse teardown failed"))
        }
        (Err(error), Err(cleanup_error)) => Err(anyhow!(
            "{error:#}; live ClickHouse teardown also failed: {cleanup_error:#}"
        )),
    }
}

fn live_client(
    prerequisites: &LivePrerequisites,
    database: &OwnedDatabaseName,
) -> Result<ClickHouseClient> {
    ClickHouseClient::new(prerequisites.clickhouse_config(database))
        .context("failed to construct owned live ClickHouse client")
}

async fn install_schema_fixture(
    clickhouse: &ClickHouseClient,
    database: &OwnedDatabaseName,
) -> Result<()> {
    let database = database.as_str();
    let insert = format!(
        r#"INSERT INTO `{database}`.`events`
(
  ingested_at, event_uid, session_id, session_date, source_name, harness, source_file,
  source_ref, record_ts, event_ts, event_kind, actor_kind, payload_type, op_kind, request_id,
  trace_id, turn_index, model, input_tokens, output_tokens, text_content, payload_json,
  event_version
)
VALUES
(
  addMonths(now64(3), -1), 'issue454-dedup', 'issue454-dedup-session', today(),
  'fixture', 'codex', 'fixture-dedup', 'fixture-old', '2026-01-02T03:04:04.500Z',
  toStartOfMinute(now64(3)), 'message', 'assistant', 'text', '', 'issue454-request', 'issue454-trace',
  1, 'old-model', 11, 0, 'old', '{{}}', 1
),
(
  now64(3), 'issue454-dedup', 'issue454-dedup-session', today(), 'fixture', 'codex',
  'fixture-dedup', 'fixture-new', '2026-01-02T03:04:05.678Z', toStartOfMinute(now64(3)), 'message',
  'assistant', 'text', '', 'issue454-request', 'issue454-trace', 1, 'new-model',
  13, 0, 'new', '{{}}', 2
),
(
  now64(3), 'issue454-web-a', 'issue454-web-session', today(), 'fixture', 'codex',
  'fixture-web', 'issue454-web-a', '2026-01-02T03:05:00.000Z', now64(3),
  'tool_call', 'assistant', 'web_search_call', 'search', '', 'issue454-trace', 1,
  '', 0, 0, '', '{{"action":{{"query":"a"}}}}', 1
),
(
  now64(3), 'issue454-web-z', 'issue454-web-session', today(), 'fixture', 'codex',
  'fixture-web', 'issue454-web-z', '2026-01-02T03:05:00.000Z', now64(3),
  'tool_call', 'assistant', 'web_search_call', 'search', '', 'issue454-trace', 1,
  '', 0, 0, '', '{{"action":{{"query":"z"}}}}', 1
)"#
    );
    clickhouse
        .request_text(&insert, None, Some(database), false, None)
        .await
        .context("failed to insert live-schema fixtures")?;
    let commentary_insert = format!(
        r#"INSERT INTO `{database}`.`events`
(
  ingested_at, event_uid, session_id, session_date, source_name, harness, source_file,
  source_ref, record_ts, event_ts, event_kind, actor_kind, payload_type, op_kind, op_status,
  request_id, trace_id, turn_index, model, input_tokens, output_tokens, text_content,
  payload_json, event_version
)
VALUES
(
  now64(3), 'issue549-user', 'issue549-commentary-session', today(), 'fixture', 'codex',
  'fixture-commentary', 'issue549-user', '2026-07-15T20:00:00.000Z', now64(3),
  'message', 'user', 'message', '', '', 'issue549-request', 'issue549-trace', 1,
  '', 0, 0, 'Check the repository.', '{{}}', 1
),
(
  now64(3), 'issue549-commentary', 'issue549-commentary-session', today(), 'fixture',
  'codex', 'fixture-commentary', 'issue549-commentary', '2026-07-15T20:00:01.000Z',
  now64(3), 'message', 'assistant', 'message', '', 'commentary', 'issue549-request',
  'issue549-trace', 1, '', 0, 0, 'I am still checking the repository.', '{{}}', 1
)"#
    );
    clickhouse
        .request_text(&commentary_insert, None, Some(database), false, None)
        .await
        .context("failed to insert commentary projection fixture")?;
    let omp_insert = format!(
        r#"INSERT INTO `{database}`.`events`
(
  ingested_at, event_uid, session_id, session_date, source_name, harness, source_file,
  source_ref, record_ts, event_ts, event_kind, actor_kind, payload_type, op_kind, request_id,
  trace_id, turn_index, model, input_tokens, output_tokens, text_content, payload_json,
  event_version
)
VALUES
(
  now64(3), 'issue568-explicit-title', 'issue568-explicit-session', today(),
  'omp', 'pi-coding-agent', '/tmp/omp/ExplicitTask.jsonl', 'issue568-explicit-title',
  '2026-07-17T01:00:00.000Z', '2026-07-17 01:00:00.000', 'unknown', 'system',
  'unknown', 'title_change', '', 'issue568-explicit-trace', 1, '', 0, 0,
  'Explicit OMP Title', '{{"type":"title_change","title":"Explicit OMP Title"}}', 1
),
(
  now64(3), 'issue568-later-name', 'issue568-explicit-session', today(),
  'omp', 'pi-coding-agent', '/tmp/omp/ExplicitTask.jsonl', 'issue568-later-name',
  '2026-07-17T01:00:01.000Z', '2026-07-17 01:00:01.000', 'session_meta', 'system',
  'session_meta', 'session_info', '', 'issue568-explicit-trace', 1, '', 0, 0,
  '', '{{"name":"Later Lower Priority Name"}}', 1
),
(
  now64(3), 'issue568-windows-fallback', 'issue568-windows-session', today(),
  'omp', 'pi-coding-agent',
  'C:\\Users\\alice\\.omp\\agent\\sessions\\project\\ReviewScope-2.jsonl',
  'issue568-windows-fallback', '2026-07-17T01:01:00.000Z', '2026-07-17 01:01:00.000',
  'message', 'user', 'user_message', '', '', 'issue568-windows-trace', 1, '', 0, 0,
  'private prompt', '{{}}', 1
),
(
  now64(3), 'issue568-main-file', '11111111-2222-4333-8444-555555555568', today(),
  'omp', 'pi-coding-agent',
  '/tmp/omp/11111111-2222-4333-8444-555555555568.jsonl',
  'issue568-main-file', '2026-07-17T01:02:00.000Z', '2026-07-17 01:02:00.000',
  'message', 'user', 'user_message', '', '', 'issue568-main-trace', 1, '', 0, 0,
  'private main prompt', '{{}}', 1
),
(
  now64(3), 'issue568-pi-title', 'issue568-pi-session', today(),
  'pi', 'pi-coding-agent', '/tmp/pi/session.jsonl', 'issue568-pi-title',
  '2026-07-17T01:03:00.000Z', '2026-07-17 01:03:00.000', 'session_meta', 'system',
  'session_meta', 'session', '', 'issue568-pi-trace', 1, '', 0, 0,
  'Pi Title', '{{"title":"Pi Title"}}', 1
),
(
  now64(3), 'issue568-pi-name', 'issue568-pi-session', today(),
  'pi', 'pi-coding-agent', '/tmp/pi/session.jsonl', 'issue568-pi-name',
  '2026-07-17T01:03:01.000Z', '2026-07-17 01:03:01.000', 'session_meta', 'system',
  'session_meta', 'session_info', '', 'issue568-pi-trace', 1, '', 0, 0,
  '', '{{"name":"Later Pi Name"}}', 1
),
(
  now64(3), 'issue568-pi-summary', 'issue568-pi-summary-session', today(),
  'pi', 'pi-coding-agent', '/tmp/pi/summary-session.jsonl', 'issue568-pi-summary',
  '2026-07-17T01:04:00.000Z', '2026-07-17 01:04:00.000', 'session_meta', 'system',
  'session_meta', 'session_info', '', 'issue568-pi-summary-trace', 1, '', 0, 0,
  '', '{{"summary":"Pi Summary"}}', 1
)"#
    );
    clickhouse
        .request_text(&omp_insert, None, Some(database), false, None)
        .await
        .context("failed to insert OMP session metadata fixtures")?;
    Ok(())
}

async fn assert_omp_session_metadata(repository: &ClickHouseConversationRepository) -> Result<()> {
    let listed = repository
        .list_mcp_sessions(
            McpSessionListFilter {
                start_unix_ms: 0,
                end_unix_ms: 4_102_444_800_000,
                mode: None,
                sort: ConversationListSort::Asc,
                harness: None,
                source_name: None,
            },
            PageRequest {
                limit: 100,
                cursor: None,
            },
        )
        .await
        .context("failed to list OMP session metadata fixtures")?;

    let explicit = listed
        .items
        .iter()
        .find(|session| session.session_id == "issue568-explicit-session")
        .context("explicit OMP session missing from listing")?;
    assert_eq!(explicit.title.as_deref(), Some("Explicit OMP Title"));
    assert_eq!(
        explicit.session_summary.as_deref(),
        Some("Explicit OMP Title")
    );

    let windows = listed
        .items
        .iter()
        .find(|session| session.session_id == "issue568-windows-session")
        .context("Windows-path OMP session missing from listing")?;
    assert_eq!(windows.title.as_deref(), Some("ReviewScope-2"));
    assert_eq!(windows.session_summary.as_deref(), Some("ReviewScope-2"));

    let main = listed
        .items
        .iter()
        .find(|session| session.session_id == "11111111-2222-4333-8444-555555555568")
        .context("UUID main-file OMP session missing from listing")?;
    assert!(main.title.is_none());
    assert!(main.session_summary.is_none());

    let pi = listed
        .items
        .iter()
        .find(|session| session.session_id == "issue568-pi-session")
        .context("Pi precedence fixture missing from listing")?;
    assert_eq!(pi.title.as_deref(), Some("Later Pi Name"));
    assert_eq!(pi.session_summary.as_deref(), Some("Later Pi Name"));

    let pi_summary = listed
        .items
        .iter()
        .find(|session| session.session_id == "issue568-pi-summary-session")
        .context("Pi summary-only fixture missing from listing")?;
    assert_eq!(pi_summary.title.as_deref(), Some("Pi Summary"));
    assert_eq!(pi_summary.session_summary.as_deref(), Some("Pi Summary"));

    for (session_id, expected_title, expected_summary) in [
        (
            "issue568-explicit-session",
            Some("Explicit OMP Title"),
            Some("Explicit OMP Title"),
        ),
        (
            "issue568-windows-session",
            Some("ReviewScope-2"),
            Some("ReviewScope-2"),
        ),
        ("11111111-2222-4333-8444-555555555568", None, None),
        ("issue568-pi-session", Some("Pi Title"), Some("Pi Title")),
        ("issue568-pi-summary-session", None, Some("Pi Summary")),
    ] {
        let opened = repository
            .get_mcp_session(session_id)
            .await
            .with_context(|| format!("failed to open session metadata fixture {session_id}"))?
            .with_context(|| format!("session metadata fixture {session_id} missing"))?;
        assert_eq!(opened.title.as_deref(), expected_title);
        assert_eq!(opened.session_summary.as_deref(), expected_summary);
    }

    Ok(())
}

#[derive(Debug)]
struct OpenSuite {
    semantic: Value,
    event_ms: u64,
    turn_ms: u64,
    session_ms: u64,
    wall_ms: u64,
}

#[derive(Debug, Deserialize, Serialize)]
struct OpenCostMetrics {
    phase: String,
    query_count: u64,
    read_rows: u64,
    read_bytes: u64,
    peak_memory: u64,
    duration_ms: u64,
}

async fn seed_mcp_open_benchmark_targets(
    clickhouse: &ClickHouseClient,
    database: &str,
) -> Result<()> {
    for (session_id, total_events, actor_expression, turn_expression) in [
        (
            "issue532-target-session",
            1_000_u64,
            "if(number % 10 = 0, 'user', 'assistant')",
            "toUInt32(intDiv(number, 10) + 1)",
        ),
        (
            "issue532-target-turn",
            1_000_u64,
            "if(number = 0, 'user', 'assistant')",
            "toUInt32(1)",
        ),
        (
            "issue532-target-event",
            500_u64,
            "if(number = 0, 'user', 'assistant')",
            "toUInt32(1)",
        ),
    ] {
        let sql = format!(
            r#"INSERT INTO `{database}`.`events`
(
  ingested_at, event_uid, session_id, session_date, source_name, harness,
  source_file, source_offset, source_ref, record_ts, event_ts, event_kind,
  actor_kind, payload_type, turn_index, text_content, payload_json, event_version
)
SELECT
  now64(3),
  concat('{session_id}-', leftPad(toString(number + 1), 4, '0')),
  '{session_id}',
  today(),
  'fixture',
  'codex',
  'issue532-bounded-open-targets',
  toUInt64(number + 1),
  concat('benchmark:', toString(number + 1)),
  '2026-07-14T18:00:00.000Z',
  toDateTime64('2026-07-14 18:00:00.000', 3),
  'message',
  {actor_expression},
  'text',
  {turn_expression},
  repeat('substantial transcript text ', 40),
  concat('{{"text":"', repeat('substantial payload ', 80), '"}}'),
  toUInt64(1)
FROM numbers({total_events})"#
        );
        clickhouse
            .request_text(&sql, None, Some(database), false, None)
            .await
            .with_context(|| format!("failed to seed canonical target {session_id}"))?;
    }
    Ok(())
}

async fn run_open_suite(
    repository: &ClickHouseConversationRepository,
    phase: &str,
    concurrent: bool,
) -> Result<OpenSuite> {
    let wall_started = Instant::now();
    let (session, session_ms, turn, turn_ms, event, event_ms) = if concurrent {
        let session = async {
            let started = Instant::now();
            let value = with_repository_query_id(
                format!("issue532-{phase}-session"),
                repository.get_mcp_session("issue532-target-session"),
            )
            .await
            .context("bounded session open failed")?
            .context("bounded session target missing")?;
            Ok::<_, anyhow::Error>((value, started.elapsed().as_millis() as u64))
        };
        let turn = async {
            let started = Instant::now();
            let value = with_repository_query_id(
                format!("issue532-{phase}-turn"),
                repository.get_mcp_turn("issue532-target-turn", 1),
            )
            .await
            .context("bounded turn open failed")?
            .context("bounded turn target missing")?;
            Ok::<_, anyhow::Error>((value, started.elapsed().as_millis() as u64))
        };
        let event = async {
            let started = Instant::now();
            let value = with_repository_query_id(
                format!("issue532-{phase}-event"),
                repository.get_mcp_event("issue532-target-event-0250"),
            )
            .await
            .context("bounded event open failed")?
            .context("bounded event target missing")?;
            Ok::<_, anyhow::Error>((value, started.elapsed().as_millis() as u64))
        };
        let (session, turn, event) = tokio::join!(session, turn, event);
        let (session, session_ms) = session?;
        let (turn, turn_ms) = turn?;
        let (event, event_ms) = event?;
        (session, session_ms, turn, turn_ms, event, event_ms)
    } else {
        let started = Instant::now();
        let session = with_repository_query_id(
            format!("issue532-{phase}-session"),
            repository.get_mcp_session("issue532-target-session"),
        )
        .await
        .context("bounded session open failed")?
        .context("bounded session target missing")?;
        let session_ms = started.elapsed().as_millis() as u64;

        let started = Instant::now();
        let turn = with_repository_query_id(
            format!("issue532-{phase}-turn"),
            repository.get_mcp_turn("issue532-target-turn", 1),
        )
        .await
        .context("bounded turn open failed")?
        .context("bounded turn target missing")?;
        let turn_ms = started.elapsed().as_millis() as u64;

        let started = Instant::now();
        let event = with_repository_query_id(
            format!("issue532-{phase}-event"),
            repository.get_mcp_event("issue532-target-event-0250"),
        )
        .await
        .context("bounded event open failed")?
        .context("bounded event target missing")?;
        let event_ms = started.elapsed().as_millis() as u64;
        (session, session_ms, turn, turn_ms, event, event_ms)
    };

    Ok(OpenSuite {
        semantic: json!({
            "session": session,
            "turn": turn,
            "event": event,
        }),
        event_ms,
        turn_ms,
        session_ms,
        wall_ms: wall_started.elapsed().as_millis() as u64,
    })
}

async fn read_open_cost_metrics(
    clickhouse: &ClickHouseClient,
    database: &str,
) -> Result<HashMap<String, OpenCostMetrics>> {
    clickhouse
        .request_text("SYSTEM FLUSH LOGS", None, None, false, None)
        .await
        .context("failed to flush query log")?;
    let rows: Vec<OpenCostMetrics> = clickhouse
        .query_rows(
            "SELECT
  extract(query_id, '^issue532-([^-]+)-') AS phase,
  toUInt64(count()) AS query_count,
  toUInt64(sum(read_rows)) AS read_rows,
  toUInt64(sum(read_bytes)) AS read_bytes,
  toUInt64(max(memory_usage)) AS peak_memory,
  toUInt64(sum(query_duration_ms)) AS duration_ms
FROM system.query_log
WHERE type = 'QueryFinish'
  AND startsWith(query_id, 'issue532-')
  AND current_database = currentDatabase()
GROUP BY phase
FORMAT JSONEachRow",
            Some(database),
        )
        .await
        .context("failed to aggregate MCP open query-log cost")?;
    Ok(rows
        .into_iter()
        .map(|row| (row.phase.clone(), row))
        .collect())
}

fn strip_uid_fields(value: &mut Value) {
    match value {
        Value::Object(object) => {
            object.retain(|key, _| !key.ends_with("uid") && key != "snapshot");
            for child in object.values_mut() {
                strip_uid_fields(child);
            }
        }
        Value::Array(items) => {
            for item in items {
                strip_uid_fields(item);
            }
        }
        _ => {}
    }
}

async fn listed_session_snapshot(
    repository: &ClickHouseConversationRepository,
    session_id: &str,
) -> Result<Value> {
    let page = repository
        .list_mcp_sessions(
            McpSessionListFilter {
                start_unix_ms: 0,
                end_unix_ms: 4_102_444_800_000,
                mode: None,
                sort: ConversationListSort::Asc,
                harness: None,
                source_name: None,
            },
            PageRequest {
                limit: 1000,
                cursor: None,
            },
        )
        .await
        .context("replay-stability list failed")?;
    let item = page
        .items
        .iter()
        .find(|item| item.session_id == session_id)
        .context("replay-stability list item missing")?;
    serde_json::to_value(item).context("failed to serialize replay-stability list item")
}

async fn migrate_fixture_to_exact_schema_032(
    clickhouse: &ClickHouseClient,
    database: &OwnedDatabaseName,
) -> Result<()> {
    let db = database.as_str();
    clickhouse
        .request_text(
            &format!("CREATE DATABASE IF NOT EXISTS `{db}`"),
            None,
            None,
            false,
            None,
        )
        .await
        .context("failed to create schema-032 fixture database")?;
    clickhouse
        .request_text(
            &format!(
                "CREATE TABLE `{db}`.`schema_migrations` (\
                 version String, name String, applied_at DateTime64(3) DEFAULT now64(3)\
                 ) ENGINE = ReplacingMergeTree(applied_at) ORDER BY version"
            ),
            None,
            Some(db),
            false,
            None,
        )
        .await
        .context("failed to create schema-032 fixture ledger")?;
    clickhouse
        .request_text(
            &format!(
                "INSERT INTO `{db}`.`schema_migrations` (version, name) \
                 VALUES ('033', 'replay_stable_events')"
            ),
            None,
            Some(db),
            false,
            None,
        )
        .await
        .context("failed to defer migration 033 for the schema fixture")?;
    clickhouse
        .run_migrations()
        .await
        .context("failed to materialize bundled migrations through schema 032")?;
    clickhouse
        .request_text(
            &format!(
                "ALTER TABLE `{db}`.`schema_migrations` DELETE WHERE version = '033' \
                 SETTINGS mutations_sync = 2"
            ),
            None,
            Some(db),
            false,
            None,
        )
        .await
        .context("failed to expose migration 033 after building schema 032")?;
    assert_eq!(
        clickhouse.pending_migration_versions().await?,
        vec!["033".to_string()],
        "fixture must contain the exact bundled schema immediately before migration 033"
    );
    Ok(())
}

async fn assert_replay_stable_migration(
    clickhouse: &ClickHouseClient,
    database: &OwnedDatabaseName,
) -> Result<()> {
    let db = database.as_str();
    let baseline_repository =
        ClickHouseConversationRepository::new(clickhouse.clone(), RepoConfig::default());
    let baseline_list =
        listed_session_snapshot(&baseline_repository, "issue532-order-session").await?;
    let mut baseline_open = serde_json::to_value(
        baseline_repository
            .get_mcp_session("issue532-order-session")
            .await
            .context("baseline replay-stability open failed")?
            .context("baseline replay-stability session missing")?,
    )?;
    strip_uid_fields(&mut baseline_open);
    let baseline_search = baseline_repository
        .search_events(SearchEventsQuery {
            query: "replacement user input".to_string(),
            session_id: Some("issue532-order-session".to_string()),
            bypass_cache: Some(true),
            strategy_hint: Some(SearchStrategyHint::Exact),
            ..SearchEventsQuery::default()
        })
        .await
        .context("baseline replay-stability search failed")?;
    let baseline_hits = baseline_search
        .hits
        .iter()
        .map(|hit| {
            json!({
                "rank": hit.rank,
                "session_id": hit.session_id,
                "event_time": hit.event_time,
                "source_name": hit.source_name,
                "harness": hit.harness,
                "event_class": hit.event_class,
                "payload_type": hit.payload_type,
                "actor_role": hit.actor_role,
                "name": hit.name,
                "phase": hit.phase,
                "source_ref": hit.source_ref,
                "text_content": hit.text_content,
            })
        })
        .collect::<Vec<_>>();
    clickhouse
        .request_text(
            &format!(
                r#"INSERT INTO `{db}`.`events`
(event_uid, session_id, session_date, source_name, harness, source_file,
 source_generation, source_line_no, source_offset, source_ref, record_ts, event_ts,
 event_kind, actor_kind, payload_type, tool_call_id, tool_name, tool_phase,
 text_content, text_preview, payload_json, origin_event_id, event_version)
VALUES
('replay-old-request-1', 'replay-stable-session', toDate('2026-01-01'), 'nac', 'nac',
 '/old/store.db', 1, 10, 100, '/old/store.db:10', '2026-01-01T00:00:00.000Z',
 toDateTime64('2026-01-01 00:00:00', 3), 'tool_call', 'assistant', 'tool_use',
 'call-stable', 'Read', 'request', 'read src/lib.rs', 'read src/lib.rs',
 '{{"logical_id":"request-stable","moraine_tool_io":{{"tool_call_id":"call-stable","parent_tool_call_id":"","tool_name":"Read","tool_phase":"request","tool_error":0,"input_json":"","output_json":"","output_text":"","project_id":"git:first","repo_rel_path":"src/lib.rs","worktree_root":"/old","source_ref":"/old/store.db:1:10"}},"type":"tool_request"}}', '', 1001),
('replay-old-request-2', 'replay-stable-session', toDate('2026-01-01'), 'nac', 'nac',
 '/new/store.db', 2, 40, 400, '/new/store.db:40', '2026-01-01T00:00:00.000Z',
 toDateTime64('2026-01-01 00:00:00', 3), 'tool_call', 'assistant', 'tool_use',
 'call-stable', 'Read', 'request', 'read src/lib.rs', 'read src/lib.rs',
 '{{"logical_id":"request-stable","moraine_tool_io":{{"tool_call_id":"call-stable","parent_tool_call_id":"","tool_name":"Read","tool_phase":"request","tool_error":0,"input_json":"","output_json":"","output_text":"","project_id":"git:second","repo_rel_path":"src/lib.rs","worktree_root":"/new","source_ref":"/new/store.db:2:40"}},"type":"tool_request"}}', '', 1002),
('replay-old-response', 'replay-stable-session', toDate('2026-01-01'), 'nac', 'nac',
 '/new/store.db', 2, 41, 401, '/new/store.db:41', '2026-01-01T00:00:01.000Z',
 toDateTime64('2026-01-01 00:00:01', 3), 'tool_result', 'tool', 'tool_result',
 'call-stable', 'Read', 'response', 'done', 'done',
 '{{"logical_id":"response-stable","request_event_uid":"replay-old-request-2","type":"tool_response"}}',
 'replay-old-request-2', 1003)"#
            ),
            None,
            Some(db),
            false,
            None,
        )
        .await
        .context("failed to insert replay-stability event fixture")?;
    for statement in [
        format!(
            "INSERT INTO `{db}`.`event_links` \
             (event_uid, linked_event_uid, linked_external_id, link_type, session_id, harness, source_name, metadata_json, event_version) \
             VALUES ('replay-old-response','replay-old-request-2','','tool_use_id','replay-stable-session','nac','nac','{{}}',1003)"
        ),
        format!(
            "INSERT INTO `{db}`.`raw_events` \
             (source_name,harness,source_file,source_generation,source_line_no,source_offset,record_ts,top_type,session_id,raw_json,raw_json_hash,event_uid) \
             VALUES ('nac','nac','/old/store.db',1,10,100,'2026-01-01T00:00:00.000Z','tool_request','replay-stable-session','{{}}',1,'replay-old-request-1'), \
                    ('nac','nac','/new/store.db',2,40,400,'2026-01-01T00:00:00.000Z','tool_request','replay-stable-session','{{}}',1,'replay-old-request-2')"
        ),
    ] {
        clickhouse
            .request_text(&statement, None, Some(db), false, None)
            .await
            .context("failed to insert replay-stability reference fixture")?;
    }

    clickhouse
        .request_text(
            &format!(
                "ALTER TABLE `{db}`.`schema_migrations` DELETE WHERE version = '033' \
                 SETTINGS mutations_sync = 2"
            ),
            None,
            Some(db),
            false,
            None,
        )
        .await
        .context("failed to reset migration 033 ledger on first pass")?;
    clickhouse
        .run_migrations()
        .await
        .context("replay-stability migration first pass failed")?;

    // Simulate interruption after the links-first EXCHANGE but before events
    // cut over: links contain v2 UIDs while the live events table contains v1
    // UIDs. The next migration must recover using the still-old events map.
    for statement in [
        format!(
            "CREATE TABLE `{db}`.`events_replay_stable_033` AS `{db}`.`events` \
             ENGINE = ReplacingMergeTree(event_version) \
             PARTITION BY cityHash64(session_id) % 64 ORDER BY (session_id, event_uid)"
        ),
        format!(
            r#"INSERT INTO `{db}`.`events_replay_stable_033`
SELECT e.* REPLACE (
  multiIf(
    session_id = 'replay-stable-session' AND event_kind = 'tool_call',
      'replay-old-request-2',
    session_id = 'replay-stable-session' AND event_kind = 'tool_result',
      'replay-old-response',
    event_uid
  ) AS event_uid,
  if(
    session_id = 'replay-stable-session' AND event_kind = 'tool_result',
    'replay-old-request-2',
    origin_event_id
  ) AS origin_event_id
)
FROM `{db}`.`events` AS e FINAL"#
        ),
        format!("EXCHANGE TABLES `{db}`.`events` AND `{db}`.`events_replay_stable_033`"),
        format!(
            "ALTER TABLE `{db}`.`schema_migrations` DELETE WHERE version = '033' \
             SETTINGS mutations_sync = 2"
        ),
    ] {
        clickhouse
            .request_text(&statement, None, Some(db), false, None)
            .await
            .context("failed to prepare migration-033 partial-cutover recovery")?;
    }
    clickhouse
        .run_migrations()
        .await
        .context("migration 033 failed to recover a links-first partial cutover")?;

    #[derive(Deserialize)]
    struct ReplayCounts {
        event_rows: u64,
        event_uids: u64,
        old_event_uids: u64,
        latest_generation: u32,
        locator_rows: u64,
        navigation_rows: u64,
        raw_rows: u64,
        raw_event_uids: u64,
        old_raw_uids: u64,
    }
    let counts: Vec<ReplayCounts> = clickhouse
        .query_rows(
            &format!(
                r#"SELECT
  (SELECT count() FROM `{db}`.`events` FINAL WHERE session_id = 'replay-stable-session') AS event_rows,
  (SELECT uniqExact(event_uid) FROM `{db}`.`events` FINAL WHERE session_id = 'replay-stable-session') AS event_uids,
  (SELECT countIf(startsWith(event_uid, 'replay-old-')) FROM `{db}`.`events` FINAL WHERE session_id = 'replay-stable-session') AS old_event_uids,
  (SELECT max(source_generation) FROM `{db}`.`events` FINAL WHERE session_id = 'replay-stable-session') AS latest_generation,
  (SELECT count() FROM `{db}`.`mcp_event_locator` FINAL WHERE session_id = 'replay-stable-session') AS locator_rows,
  (SELECT count() FROM `{db}`.`mcp_event_navigation` FINAL WHERE session_id = 'replay-stable-session') AS navigation_rows,
  (SELECT count() FROM `{db}`.`raw_events` WHERE session_id = 'replay-stable-session') AS raw_rows,
  (SELECT uniqExact(event_uid) FROM `{db}`.`raw_events` WHERE session_id = 'replay-stable-session') AS raw_event_uids,
  (SELECT countIf(startsWith(event_uid, 'replay-old-')) FROM `{db}`.`raw_events` WHERE session_id = 'replay-stable-session') AS old_raw_uids
FORMAT JSONEachRow"#
            ),
            Some(db),
        )
        .await
        .context("failed to read replay-stability counts")?;
    let counts = counts.first().context("missing replay-stability counts")?;
    assert_eq!(counts.event_rows, 2);
    assert_eq!(counts.event_uids, 2);
    assert_eq!(counts.old_event_uids, 0);
    assert_eq!(counts.latest_generation, 2);
    assert_eq!(counts.locator_rows, 2);
    assert_eq!(counts.navigation_rows, 2);
    assert_eq!(counts.raw_rows, 2);
    assert_eq!(counts.raw_event_uids, 2);
    assert_eq!(counts.old_raw_uids, 2);

    #[derive(Deserialize)]
    struct ReplayLink {
        request_uid: String,
        origin_event_id: String,
        linked_event_uid: String,
    }
    let links: Vec<ReplayLink> = clickhouse
        .query_rows(
            &format!(
                r#"SELECT request.event_uid AS request_uid,
  response.origin_event_id AS origin_event_id,
  link.linked_event_uid AS linked_event_uid
FROM `{db}`.`events` AS request FINAL
CROSS JOIN `{db}`.`events` AS response FINAL
INNER JOIN `{db}`.`event_links` AS link FINAL ON link.event_uid = response.event_uid
WHERE request.session_id = 'replay-stable-session'
  AND request.event_kind = 'tool_call'
  AND response.session_id = 'replay-stable-session'
  AND response.event_kind = 'tool_result'
FORMAT JSONEachRow"#
            ),
            Some(db),
        )
        .await
        .context("failed to read replay-stability links")?;
    let link = links.first().context("missing replay-stability link")?;
    assert_eq!(
        link.request_uid,
        "9e4f03ed718cc58482613c6cea7f65435f15cd26c46c87291a16431ad310c3f6"
    );
    assert_eq!(link.origin_event_id, link.request_uid);
    assert_eq!(link.linked_event_uid, link.request_uid);

    let candidate_repository =
        ClickHouseConversationRepository::new(clickhouse.clone(), RepoConfig::default());
    let candidate_list =
        listed_session_snapshot(&candidate_repository, "issue532-order-session").await?;
    assert_eq!(candidate_list, baseline_list);
    let mut candidate_open = serde_json::to_value(
        candidate_repository
            .get_mcp_session("issue532-order-session")
            .await
            .context("candidate replay-stability open failed")?
            .context("candidate replay-stability session missing")?,
    )?;
    strip_uid_fields(&mut candidate_open);
    assert_eq!(candidate_open, baseline_open);

    let candidate_search = candidate_repository
        .search_events(SearchEventsQuery {
            query: "replacement user input".to_string(),
            session_id: Some("issue532-order-session".to_string()),
            bypass_cache: Some(true),
            strategy_hint: Some(SearchStrategyHint::Exact),
            ..SearchEventsQuery::default()
        })
        .await
        .context("candidate replay-stability search failed")?;
    let candidate_hits = candidate_search
        .hits
        .iter()
        .map(|hit| {
            json!({
                "rank": hit.rank,
                "session_id": hit.session_id,
                "event_time": hit.event_time,
                "source_name": hit.source_name,
                "harness": hit.harness,
                "event_class": hit.event_class,
                "payload_type": hit.payload_type,
                "actor_role": hit.actor_role,
                "name": hit.name,
                "phase": hit.phase,
                "source_ref": hit.source_ref,
                "text_content": hit.text_content,
            })
        })
        .collect::<Vec<_>>();
    assert_eq!(candidate_hits, baseline_hits);
    Ok(())
}

#[tokio::test]
#[ignore = "requires wrapper-owned live ClickHouse and destructive opt-in"]
async fn live_schema_semantics_and_teardown() -> Result<()> {
    let prerequisites = LivePrerequisites::load()?;
    let database = prepare_owned_database_identity(&prerequisites.sandbox_id)?;
    let clickhouse = live_client(&prerequisites, &database)?;
    assert_owned_database_census_empty(&clickhouse, "before mutation").await?;
    let outcome = async {
        assert_live_schema_032_replay_stable_upgrade(&clickhouse, &database).await?;
        cleanup_database(&clickhouse, &database)
            .await
            .context("failed to reset database after schema-032 upgrade proof")?;
        assert_owned_database_census_empty(&clickhouse, "after schema-032 upgrade proof").await?;


        clickhouse
            .run_migrations()
            .await
            .context("failed to migrate temporary live-schema database")?;
        let repository =
            ClickHouseConversationRepository::new(clickhouse.clone(), RepoConfig::default());

        let empty = repository
            .analytics_series(AnalyticsRange::FifteenMinutes)
            .await
            .context("empty-window analytics read failed")?;
        assert!(empty.tokens.is_empty());
        assert!(empty.turns.is_empty());
        assert!(empty.concurrent_sessions.is_empty());
        let empty_heartbeat = repository
            .latest_ingest_heartbeat()
            .await
            .context("empty heartbeat read failed")?;
        assert!(empty_heartbeat.table_present);
        assert!(empty_heartbeat.latest.is_none());

        clickhouse
            .request_text(
                &format!(
                    "ALTER TABLE `{}`.`ingest_heartbeats` DROP COLUMN IF EXISTS backend_sinks",
                    database.as_str()
                ),
                None,
                Some(database.as_str()),
                false,
                None,
            )
            .await
            .context("failed to remove optional heartbeat column")?;
        let legacy_repository =
            ClickHouseConversationRepository::new(clickhouse.clone(), RepoConfig::default());
        let legacy_heartbeat = legacy_repository
            .latest_ingest_heartbeat()
            .await
            .context("legacy heartbeat read failed")?;
        assert!(legacy_heartbeat.table_present);
        assert!(legacy_heartbeat.latest.is_none());

        install_schema_fixture(&clickhouse, &database).await?;
        assert_omp_session_metadata(&repository).await?;
        let commentary_turn = repository
            .get_mcp_turn("issue549-commentary-session", 1)
            .await
            .context("commentary turn projection failed")?
            .context("commentary turn missing")?;
        assert!(!commentary_turn.completed);
        assert!(commentary_turn.terminal_event_uid.is_none());
        assert!(commentary_turn.final_response_summary.is_none());
        assert!(commentary_turn.events.iter().any(|event| {
            event.event_uid == "issue549-commentary"
                && event.event_type == "assistant_response"
                && event.phase == "commentary"
        }));


        #[derive(Deserialize)]
        struct TurnTimestampTypeRow {
            started_at_type: String,
            ended_at_type: String,
        }
        let turn_timestamp_types: Vec<TurnTimestampTypeRow> = clickhouse
            .query_rows(
                &format!(
                    "SELECT toTypeName(started_at) AS started_at_type, \
                     toTypeName(ended_at) AS ended_at_type \
                     FROM `{}`.`v_turn_summary` \
                     WHERE session_id = 'issue454-dedup-session' \
                     FORMAT JSONEachRow",
                    database.as_str()
                ),
                Some(database.as_str()),
            )
            .await
            .context("turn summary timestamp type query failed")?;
        assert_eq!(turn_timestamp_types.len(), 1);
        assert!(
            turn_timestamp_types[0]
                .started_at_type
                .starts_with("DateTime64(3"),
            "started_at must remain typed: {}",
            turn_timestamp_types[0].started_at_type
        );
        assert!(
            turn_timestamp_types[0]
                .ended_at_type
                .starts_with("DateTime64(3"),
            "ended_at must remain typed: {}",
            turn_timestamp_types[0].ended_at_type
        );

        #[derive(Deserialize)]
        struct ModelRow {
            model: String,
        }
        let canonical: Vec<ModelRow> = clickhouse
            .query_rows(
                &format!(
                    "SELECT model FROM (SELECT * FROM `{}`.`events` FINAL \
                     SETTINGS do_not_merge_across_partitions_select_final = 0) \
                     WHERE event_uid = 'issue454-dedup' FORMAT JSONEachRow",
                    database.as_str()
                ),
                Some(database.as_str()),
            )
            .await
            .context("canonical cross-partition fixture query failed")?;
        assert_eq!(canonical.len(), 1);
        assert_eq!(canonical[0].model, "new-model");
        let stale_predicate: Vec<ModelRow> = clickhouse
            .query_rows(
                &format!(
                    "SELECT model FROM (SELECT * FROM `{}`.`events` FINAL \
                     SETTINGS do_not_merge_across_partitions_select_final = 0) \
                     WHERE event_uid = 'issue454-dedup' AND model = 'old-model' \
                     FORMAT JSONEachRow",
                    database.as_str()
                ),
                Some(database.as_str()),
            )
            .await
            .context("canonical outer-predicate query failed")?;
        assert!(stale_predicate.is_empty());

        let populated_repository =
            ClickHouseConversationRepository::new(clickhouse.clone(), RepoConfig::default());
        let analytics = populated_repository
            .analytics_series(AnalyticsRange::FifteenMinutes)
            .await
            .context("populated analytics read failed")?;
        assert!(analytics
            .tokens
            .iter()
            .any(|point| point.model == "new-model"));
        assert!(!analytics
            .tokens
            .iter()
            .any(|point| point.model == "old-model"));
        let sessions = populated_repository
            .list_session_analytics(SessionAnalyticsQuery {
                lookback: SessionLookback::All,
                limit: 50,
            })
            .await
            .context("populated session analytics read failed")?;
        let deduped = sessions
            .iter()
            .find(|session| session.summary.session_id == "issue454-dedup-session")
            .context("deduped fixture session missing")?;
        assert_eq!(deduped.summary.total_events, 1);
        assert_eq!(deduped.models, vec!["new-model"]);
        const FIXTURE_EVENT_UNIX_MS: i64 = 1_767_323_045_678;
        assert_eq!(deduped.summary.first_event_unix_ms, FIXTURE_EVENT_UNIX_MS);
        assert_eq!(deduped.summary.last_event_unix_ms, FIXTURE_EVENT_UNIX_MS);

        let listed_turns = populated_repository
            .list_turns(
                "issue454-dedup-session",
                TurnListFilter::default(),
                PageRequest::default(),
            )
            .await
            .context("typed turn list projection failed")?;
        assert_eq!(listed_turns.items.len(), 1);
        assert_eq!(
            listed_turns.items[0].started_at_unix_ms,
            FIXTURE_EVENT_UNIX_MS
        );
        assert_eq!(
            listed_turns.items[0].ended_at_unix_ms,
            FIXTURE_EVENT_UNIX_MS
        );

        let mcp_session = populated_repository
            .get_mcp_session("issue454-dedup-session")
            .await
            .context("typed MCP session projection failed")?
            .context("MCP fixture session missing")?;
        assert_eq!(mcp_session.turns.len(), 1);
        assert_eq!(
            mcp_session.turns[0].metadata.started_at_unix_ms,
            FIXTURE_EVENT_UNIX_MS
        );
        let mcp_turn = populated_repository
            .get_mcp_turn("issue454-dedup-session", 1)
            .await
            .context("bounded MCP turn projection failed")?
            .context("bounded MCP turn missing")?;
        assert_eq!(mcp_turn.events.len(), 1);
        assert_eq!(mcp_turn.events[0].text_preview.as_deref(), Some("new"));
        let mcp_event = populated_repository
            .get_mcp_event("issue454-dedup")
            .await
            .context("bounded MCP event projection failed")?
            .context("bounded MCP event missing")?;
        assert_eq!(mcp_event.event.text_content, "new");
        assert_eq!(mcp_event.parent_turn.turn_seq, 1);
        let turn = populated_repository
            .get_turn("issue454-dedup-session", 1)
            .await
            .context("view-only turn read failed")?
            .context("view-only fixture turn missing")?;
        assert_eq!(turn.summary.total_events, 1);
        assert_eq!(turn.summary.started_at_unix_ms, FIXTURE_EVENT_UNIX_MS);
        assert_eq!(turn.summary.ended_at_unix_ms, FIXTURE_EVENT_UNIX_MS);
        assert_eq!(turn.events.len(), 1);
        assert_eq!(turn.events[0].text_content, "new");
        let web = populated_repository
            .list_web_searches(1000)
            .await
            .context("same-millisecond web feed read failed")?;
        let fixture_refs = web
            .iter()
            .filter(|event| event.session_id == "issue454-web-session")
            .map(|event| event.source_ref.as_str())
            .collect::<Vec<_>>();
        assert_eq!(fixture_refs, vec!["issue454-web-z", "issue454-web-a"]);

        clickhouse
            .request_text(
                &format!(
                    r#"INSERT INTO `{0}`.`events`
(
  ingested_at, event_uid, session_id, session_date, source_name, harness, source_file,
  source_ref, record_ts, event_ts, event_kind, actor_kind, payload_type, op_kind, request_id,
  trace_id, turn_index, model, input_tokens, output_tokens, text_content, payload_json,
  event_version
)
SELECT
  now64(3), 'issue454-dedup', 'issue454-dedup-session', today(), 'fixture', 'codex',
  'fixture-dedup', 'fixture-final', '2026-01-02T03:04:06.789Z',
  (SELECT any(event_ts) FROM `{0}`.`events` FINAL WHERE event_uid = 'issue454-dedup'),
  'message', 'assistant', 'text', '', 'issue454-request', 'issue454-trace', 1,
  'final-model', 17, 0, 'replacement-final', '{{}}', 3"#,
                    database.as_str()
                ),
                None,
                Some(database.as_str()),
                false,
                None,
            )
            .await
            .context("failed to insert canonical replacement fixture")?;

        let replaced_turn = populated_repository
            .get_mcp_turn("issue454-dedup-session", 1)
            .await
            .context("replacement MCP turn projection failed")?
            .context("replacement MCP turn missing")?;
        assert_eq!(
            replaced_turn.final_response_summary.as_deref(),
            Some("replacement-final")
        );
        let replaced_event = populated_repository
            .get_mcp_event("issue454-dedup")
            .await
            .context("replacement MCP event projection failed")?
            .context("replacement MCP event missing")?;
        assert_eq!(replaced_event.event.text_content, "replacement-final");

        clickhouse
            .request_text(
                &format!(
                    r#"INSERT INTO `{0}`.`events`
(
  ingested_at, event_uid, session_id, session_date, source_name, harness, source_file,
  source_ref, record_ts, event_ts, event_kind, actor_kind, payload_type, op_kind, request_id,
  trace_id, turn_index, model, input_tokens, output_tokens, text_content, payload_json,
  event_version
)
SELECT
  now64(3), 'issue454-dedup', 'issue454-dedup-session', today(), 'fixture', 'codex',
  'fixture-dedup', 'fixture-resumed', '2026-01-02T03:04:07.890Z',
  (SELECT any(event_ts) FROM `{0}`.`events` FINAL WHERE event_uid = 'issue454-dedup'),
  'message', 'assistant', 'text', '', 'issue454-request', 'issue454-trace', 1,
  'resumed-model', 19, 0, 'replacement-resumed', '{{}}', 4"#,
                    database.as_str()
                ),
                None,
                Some(database.as_str()),
                false,
                None,
            )
            .await
            .context("failed to insert unprojected canonical replacement")?;
        let latest_event = populated_repository
            .get_mcp_event("issue454-dedup")
            .await
            .context("canonical event read failed after replacement")?
            .context("canonical event missing after replacement")?;
        assert_eq!(latest_event.event.text_content, "replacement-resumed");
        clickhouse
            .request_text(
                &format!(
                    r#"INSERT INTO `{}`.`events`
(
  ingested_at, event_uid, session_id, session_date, source_name, harness, source_file,
  source_ref, record_ts, event_ts, event_kind, actor_kind, payload_type, turn_index,
  text_content, payload_json, event_version
)
VALUES
  (now64(3), 'issue532-order-a', 'issue532-order-session', today(), 'fixture', 'codex',
   'fixture-order', 'order-a-v1', '2026-07-14T18:00:00.000Z', toDateTime64('2026-07-14 18:00:00', 3),
   'message', 'user', 'text', 0, 'first user input', '{{}}', 1),
  (now64(3), 'issue532-order-b', 'issue532-order-session', today(), 'fixture', 'codex',
   'fixture-order', 'order-b-v1', '2026-07-14T18:00:01.000Z', toDateTime64('2026-07-14 18:00:00', 3),
   'message', 'assistant', 'text', 0, 'initial assistant response', '{{}}', 1),
  (now64(3), 'issue532-order-c', 'issue532-order-session', today(), 'fixture', 'codex',
   'fixture-order', 'order-c-v1', '2026-07-14T18:00:02.000Z', toDateTime64('2026-07-14 18:00:00', 3),
   'queue_operation', 'assistant', 'task_complete', 0, '', '{{}}', 1)"#,
                    database.as_str()
                ),
                None,
                Some(database.as_str()),
                false,
                None,
            )
            .await
            .context("failed to insert ordering fixture")?;
        clickhouse
            .request_text(
                &format!(
                    r#"INSERT INTO `{}`.`events`
(
  ingested_at, event_uid, session_id, session_date, source_name, harness, source_file,
  source_ref, record_ts, event_ts, event_kind, actor_kind, payload_type, turn_index,
  text_content, payload_json, event_version
)
VALUES
  (now64(3), 'issue532-order-b', 'issue532-order-session', today(), 'fixture', 'codex',
   'fixture-order', 'order-b-v2', '2026-07-14T17:59:59.000Z', toDateTime64('2026-07-14 18:00:00', 3),
   'message', 'user', 'text', 0, 'replacement user input', '{{}}', 2)"#,
                    database.as_str()
                ),
                None,
                Some(database.as_str()),
                false,
                None,
            )
            .await
            .context("failed to insert ordering replacement")?;

        let reordered = populated_repository
            .get_mcp_event("issue532-order-b")
            .await
            .context("reordered MCP event projection failed")?
            .context("reordered MCP event missing")?;
        assert_eq!(reordered.event.event_order, 1);
        assert_eq!(reordered.event.turn_seq, 1);
        assert_eq!(reordered.event.text_content, "replacement user input");
        assert_eq!(
            reordered
                .next_event
                .as_ref()
                .map(|event| event.event_uid.as_str()),
            Some("issue532-order-a")
        );
        assert_eq!(
            reordered.next_turn.as_ref().map(|turn| turn.turn_seq),
            Some(2)
        );
        let reordered_session = populated_repository
            .get_mcp_session("issue532-order-session")
            .await
            .context("reordered MCP session projection failed")?
            .context("reordered MCP session missing")?;
        assert_eq!(reordered_session.turns.len(), 2);
        assert!(reordered_session.completed);
        assert_replay_stable_migration(&clickhouse, &database).await?;
        Ok(())
    }
    .await;

    let cleanup = cleanup_database(&clickhouse, &database).await;
    let census = assert_owned_database_census_empty(&clickhouse, "after cleanup").await;
    finish_with_cleanup(outcome, finish_with_cleanup(cleanup, census))
}

async fn assert_live_schema_032_replay_stable_upgrade(
    clickhouse: &ClickHouseClient,
    database: &OwnedDatabaseName,
) -> Result<()> {
    let db = database.as_str();
    migrate_fixture_to_exact_schema_032(clickhouse, database).await?;

    clickhouse
            .request_text(
                &format!(
                    r#"INSERT INTO `{db}`.`events`
(event_uid, session_id, session_date, source_name, harness, source_file,
 source_generation, source_line_no, source_offset, source_ref, record_ts, event_ts,
 event_kind, actor_kind, payload_type, tool_call_id, tool_name, tool_phase,
 text_content, text_preview, payload_json, origin_event_id, event_version)
VALUES
('schema32-request-old', 'schema32-session', toDate('2026-01-01'), 'nac', 'nac',
 '/old/store.db', 1, 10, 100, '/old/store.db:10', '2026-01-01T00:00:00.000Z',
 toDateTime64('2026-01-01 00:00:00', 3), 'tool_call', 'assistant', 'tool_use',
 'call-stable', 'Read', 'request', 'same request', 'same request',
 '{{"cwd":"/old","logical_id":"request-stable","message":"same request","moraine_tool_io":{{"source_ref":"/old/store.db:1:10","tool_call_id":"call-stable","tool_name":"Read","tool_phase":"request"}},"timestamp":"2026-01-01T00:00:00Z"}}', '', 1001),
('schema32-request-new', 'schema32-session', toDate('2026-01-01'), 'nac', 'nac',
 '/new/store.db', 9, 40, 400, '/new/store.db:40', '2026-07-01T00:00:00.000Z',
 toDateTime64('2026-07-01 00:00:00', 3), 'tool_call', 'assistant', 'tool_use',
 'call-stable', 'Read', 'request', 'same request', 'same request',
 '{{"cwd":"/new","logical_id":"request-stable","message":"same request","moraine_tool_io":{{"source_ref":"/new/store.db:9:40","tool_call_id":"call-stable","tool_name":"Read","tool_phase":"request"}},"timestamp":"2026-07-01T00:00:00Z"}}', '', 1002),
('schema32-response', 'schema32-session', toDate('2026-01-01'), 'nac', 'nac',
 '/new/store.db', 9, 41, 401, '/new/store.db:41', '2026-07-01T00:00:01.000Z',
 toDateTime64('2026-07-01 00:00:01', 3), 'tool_result', 'tool', 'tool_result',
 'call-stable', 'Read', 'response', 'done', 'done',
 '{{"logical_id":"response-stable","request_event_uid":"schema32-request-new","type":"tool_response"}}',
 'schema32-request-new', 1003),
('00000000aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', 'schema32-qwen', toDate('2026-01-01'), 'custom-qwen-source', 'qwen-code',
 '/old/qwen.jsonl', 1, 50, 500, '/old/qwen.jsonl:50', '2026-01-01T00:00:02.000Z',
 toDateTime64('2026-01-01 00:00:02', 3), 'reasoning', 'assistant', 'thinking',
 '', '', '', 'first', 'first', '{{"uuid":"assistant-1","parentUuid":null,"part":{{"text":"first","thought":true}}}}', '', 1004),
('00000001bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb', 'schema32-qwen', toDate('2026-01-01'), 'custom-qwen-source', 'qwen-code',
 '/old/qwen.jsonl', 1, 50, 500, '/old/qwen.jsonl:50', '2026-01-01T00:00:02.000Z',
 toDateTime64('2026-01-01 00:00:02', 3), 'message', 'assistant', 'agent_message',
 '', '', '', 'second', 'second', '{{"uuid":"assistant-1","parentUuid":null,"part":{{"text":"second"}}}}', '', 1005)"#
                ),
                None,
                Some(db),
                false,
                None,
            )
            .await
            .context("failed to insert schema-032 event fixture")?;
    clickhouse
            .request_text(
                &format!(
                    "INSERT INTO `{db}`.`event_links` \
                     (event_uid, linked_event_uid, linked_external_id, link_type, session_id, harness, source_name, metadata_json, event_version) \
                     VALUES ('schema32-response','schema32-request-new','','tool_use_id','schema32-session','nac','nac','{{}}',1003)"
                ),
                None,
                Some(db),
                false,
                None,
            )
            .await
            .context("failed to insert schema-032 link fixture")?;

    clickhouse
        .run_migrations()
        .await
        .context("failed to upgrade exact schema 032 through migration 033")?;
    let first_qwen_uids = clickhouse
        .request_text(
            &format!(
                "SELECT arrayStringConcat(groupArray(event_uid), ',') FROM (\
                   SELECT event_uid FROM `{db}`.`events` FINAL \
                   WHERE session_id = 'schema32-qwen' \
                   ORDER BY source_offset, JSONExtractUInt(payload_json, 'moraine_emission_index')\
                 )"
            ),
            None,
            Some(db),
            false,
            None,
        )
        .await
        .context("failed to capture first-pass Qwen UIDs")?;
    clickhouse
        .request_text(
            &format!(
                "ALTER TABLE `{db}`.`schema_migrations` DELETE WHERE version = '033' \
                 SETTINGS mutations_sync = 2"
            ),
            None,
            Some(db),
            false,
            None,
        )
        .await
        .context("failed to expose migration 033 for Qwen replay")?;
    clickhouse
        .run_migrations()
        .await
        .context("failed to rerun migration 033 over upgraded Qwen payloads")?;

    #[derive(Deserialize)]
    struct UpgradeResult {
        event_rows: u64,
        event_uids: u64,
        locator_rows: u64,
        navigation_rows: u64,
        request_uid: String,
        response_origin_uid: String,
        linked_uid: String,
        qwen_emission_indexes: String,
        qwen_uids: String,
        qwen_trace_text: String,
    }
    let rows: Vec<UpgradeResult> = clickhouse
            .query_rows(
                &format!(
                    r#"SELECT
  (SELECT count() FROM `{db}`.`events` FINAL WHERE session_id = 'schema32-session') AS event_rows,
  (SELECT uniqExact(event_uid) FROM `{db}`.`events` FINAL WHERE session_id = 'schema32-session') AS event_uids,
  (SELECT count() FROM `{db}`.`mcp_event_locator` FINAL WHERE session_id = 'schema32-session') AS locator_rows,
  (SELECT count() FROM `{db}`.`mcp_event_navigation` FINAL WHERE session_id = 'schema32-session') AS navigation_rows,
  (SELECT arrayStringConcat(groupArray(toString(emission_index)), ',') FROM (
    SELECT emission_index FROM `{db}`.`mcp_event_navigation` FINAL
    WHERE session_id = 'schema32-qwen'
    ORDER BY sort_time, source_file, source_generation, source_offset,
      source_line_no, emission_index, event_uid
  )) AS qwen_emission_indexes,
  (SELECT arrayStringConcat(groupArray(event_uid), ',') FROM (
    SELECT event_uid FROM `{db}`.`events` FINAL
    WHERE session_id = 'schema32-qwen'
    ORDER BY source_offset, JSONExtractUInt(payload_json, 'moraine_emission_index')
  )) AS qwen_uids,
  (SELECT arrayStringConcat(groupArray(text_content), ',') FROM (
    SELECT text_content FROM `{db}`.`v_conversation_trace`
    WHERE session_id = 'schema32-qwen' ORDER BY event_order
  )) AS qwen_trace_text,
  request.event_uid AS request_uid,
  response.origin_event_id AS response_origin_uid,
  link.linked_event_uid AS linked_uid
FROM `{db}`.`events` AS request FINAL
CROSS JOIN `{db}`.`events` AS response FINAL
INNER JOIN `{db}`.`event_links` AS link FINAL ON link.event_uid = response.event_uid
WHERE request.session_id = 'schema32-session' AND request.event_kind = 'tool_call'
  AND response.session_id = 'schema32-session' AND response.event_kind = 'tool_result'
FORMAT JSONEachRow"#
                ),
                Some(db),
            )
            .await
            .context("failed to verify schema-032 upgrade")?;
    let row = rows.first().context("missing schema-032 upgrade result")?;
    assert_eq!(row.event_rows, 2);
    assert_eq!(row.event_uids, 2);
    assert_eq!(row.locator_rows, 2);
    assert_eq!(row.navigation_rows, 2);
    assert_eq!(row.response_origin_uid, row.request_uid);
    assert_eq!(row.linked_uid, row.request_uid);
    assert_eq!(row.qwen_emission_indexes, "1,2");
    assert_eq!(row.qwen_uids, first_qwen_uids.trim());
    assert_eq!(row.qwen_trace_text, "first,second");
    Ok(())
}

#[tokio::test]
#[ignore = "requires wrapper-owned live ClickHouse, destructive opt-in, and ~2 GB free"]
async fn live_schema_032_replay_stable_upgrade_stays_within_memory_budget() -> Result<()> {
    const EVENT_ROWS: u64 = 200_000;
    const PAYLOAD_BYTES: usize = 2_048;

    let prerequisites = LivePrerequisites::load()?;
    let database = prepare_owned_database_identity(&prerequisites.sandbox_id)?;
    let clickhouse = live_client(&prerequisites, &database)?;
    assert_owned_database_census_empty(&clickhouse, "before memory-bounded upgrade").await?;

    let outcome = async {
        migrate_fixture_to_exact_schema_032(&clickhouse, &database).await?;
        let db = database.as_str();
        for view in [
            "mv_mcp_event_locator_from_events",
            "mv_mcp_event_navigation_from_events",
            "mv_search_postings",
            "mv_file_attention_project_roots_from_events",
        ] {
            clickhouse
                .request_text(
                    &format!("DROP VIEW IF EXISTS `{db}`.`{view}`"),
                    None,
                    Some(db),
                    false,
                    None,
                )
                .await
                .with_context(|| format!("failed to suspend {view} while seeding fixture"))?;
        }
        const SEED_BATCH_ROWS: u64 = 10_000;
        for offset in (0..EVENT_ROWS).step_by(SEED_BATCH_ROWS as usize) {
            let rows = SEED_BATCH_ROWS.min(EVENT_ROWS - offset);
            clickhouse
                .request_text(
                    &format!(
                        r#"INSERT INTO `{db}`.`events`
(event_uid, session_id, session_date, source_name, harness, source_file,
 source_generation, source_line_no, source_offset, source_ref, record_ts, event_ts,
 event_kind, actor_kind, payload_type, text_content, text_preview, payload_json,
 event_version)
SELECT
  lower(hex(SHA256(toString(number)))),
  concat('memory-session-', toString(number % 1000)),
  toDate('2026-01-01'),
  'memory-fixture',
  'codex',
  '/memory/fixture.jsonl',
  toUInt32(1),
  number + 1,
  number * 4096,
  concat('/memory/fixture.jsonl:', toString(number + 1)),
  '2026-01-01T00:00:00.000Z',
  toDateTime64('2026-01-01 00:00:00', 3),
  'message',
  'assistant',
  'agent_message',
  'bounded migration fixture',
  'bounded migration fixture',
  concat('{{"blob":"', repeat('x', {PAYLOAD_BYTES}), '","ordinal":', toString(number), '}}'),
  number + 1
FROM numbers({offset}, {rows})
SETTINGS max_block_size = 8192,
  min_insert_block_size_rows = 8192,
  min_insert_block_size_bytes = 16777216,
  max_threads = 4,
  max_memory_usage = 536870912"#
                    ),
                    None,
                    Some(db),
                    false,
                    None,
                )
                .await
                .with_context(|| format!("failed to seed fixture rows {offset}..{}", offset + rows))?;
        }

        clickhouse
            .run_migrations()
            .await
            .context("migration 033 exceeded its bounded rewrite budget")?;

        #[derive(Deserialize)]
        struct Counts {
            rows: u64,
            uids: u64,
            locator_rows: u64,
            navigation_rows: u64,
        }
        let counts: Vec<Counts> = clickhouse
            .query_rows(
                &format!(
                    r#"SELECT
  (SELECT count() FROM `{db}`.`events` FINAL WHERE source_name = 'memory-fixture') AS rows,
  (SELECT uniqExact(event_uid) FROM `{db}`.`events` FINAL WHERE source_name = 'memory-fixture') AS uids,
  (SELECT count() FROM `{db}`.`mcp_event_locator` FINAL WHERE source_name = 'memory-fixture') AS locator_rows,
  (SELECT count() FROM `{db}`.`mcp_event_navigation` FINAL WHERE source_name = 'memory-fixture') AS navigation_rows
FORMAT JSONEachRow"#
                ),
                Some(db),
            )
            .await
            .context("failed to verify memory-bounded migration output")?;
        let counts = counts.first().context("missing memory-bounded counts")?;
        assert_eq!(counts.rows, EVENT_ROWS);
        assert_eq!(counts.uids, EVENT_ROWS);
        assert_eq!(counts.locator_rows, EVENT_ROWS);
        assert_eq!(counts.navigation_rows, EVENT_ROWS);
        Ok(())
    }
    .await;

    let cleanup = cleanup_database(&clickhouse, &database).await;
    let census =
        assert_owned_database_census_empty(&clickhouse, "after memory-bounded upgrade").await;
    finish_with_cleanup(outcome, finish_with_cleanup(cleanup, census))
}

#[tokio::test]
#[ignore = "requires wrapper-owned live ClickHouse, destructive opt-in, and ~2 GB free"]
async fn live_mcp_open_boundedness_benchmark() -> Result<()> {
    const UNRELATED_EVENTS: u64 = 1_000_000;
    const UNRELATED_SESSIONS: u64 = 100_000;
    const CANONICAL_BATCH_SIZE: u64 = 10_000;
    const READ_ROW_GROWTH_BUDGET: u64 = 32_768;
    const READ_BYTE_GROWTH_BUDGET: u64 = 16 * 1024 * 1024;
    const MEMORY_GROWTH_BUDGET: u64 = 64 * 1024 * 1024;

    let prerequisites = LivePrerequisites::load()?;
    let database = prepare_owned_database_identity(&prerequisites.sandbox_id)?;
    let clickhouse = live_client(&prerequisites, &database)?;
    assert_owned_database_census_empty(&clickhouse, "before bounded-open benchmark").await?;

    let outcome = async {
        clickhouse
            .run_migrations()
            .await
            .context("failed to migrate bounded-open benchmark database")?;
        install_schema_fixture(&clickhouse, &database).await?;
        seed_mcp_open_benchmark_targets(&clickhouse, database.as_str()).await?;
        let repository =
            ClickHouseConversationRepository::new(clickhouse.clone(), RepoConfig::default());

        // Warm code paths before either measured phase; all measured IDs remain
        // distinct and uncached at the MCP repository boundary.
        let _ = run_open_suite(&repository, "warm", false).await?;
        let before = run_open_suite(&repository, "before", false).await?;

        let database_name = database.as_str();
        for offset in (0..UNRELATED_EVENTS).step_by(CANONICAL_BATCH_SIZE as usize) {
            let batch_size = CANONICAL_BATCH_SIZE.min(UNRELATED_EVENTS - offset);
            let seed_canonical_events = format!(
                "INSERT INTO `{database_name}`.`events`
                 (ingested_at, event_uid, session_id, session_date, source_name, harness, source_file,
                  source_ref, record_ts, event_ts, event_kind, actor_kind, payload_type, turn_index,
                  text_content, payload_json, event_version)
                 SELECT
                   now64(3),
                   concat('issue532-unrelated-event-', leftPad(toString(event_number), 8, '0')),
                   concat('issue532-unrelated-session-', leftPad(toString(intDiv(event_number, 10)), 7, '0')),
                   today(), 'fixture', 'codex', 'issue532-unrelated-corpus',
                   concat('issue532-unrelated:', toString(event_number)),
                   '2026-07-14T18:00:00.000Z', now64(3), 'message', 'assistant', 'text', toUInt32(1),
                   repeat('substantial transcript text ', 20),
                   concat('{{\"text\":\"', repeat('substantial payload ', 40), '\"}}'),
                   toUInt64(event_number + 1)
                 FROM (
                   SELECT number + {offset} AS event_number
                   FROM numbers({batch_size})
                 )"
            );
            clickhouse
                .request_text(
                    &seed_canonical_events,
                    None,
                    Some(database_name),
                    false,
                    None,
                )
                .await
                .context("failed to seed one-million-event canonical corpus")?;
        }

        let after = run_open_suite(&repository, "after", false).await?;
        let concurrent = run_open_suite(&repository, "concurrent", true).await?;
        let recovery = run_open_suite(&repository, "recovery", false).await?;
        assert_eq!(after.semantic, before.semantic);
        assert_eq!(concurrent.semantic, before.semantic);
        assert_eq!(recovery.semantic, before.semantic);
        assert!(
            after.event_ms <= 500,
            "warm event open exceeded 500 ms SLA: {} ms",
            after.event_ms
        );
        assert!(
            after.turn_ms <= 750,
            "warm turn open exceeded 750 ms SLA: {} ms",
            after.turn_ms
        );
        assert!(
            after.session_ms <= 1_000,
            "warm session open exceeded 1,000 ms SLA: {} ms",
            after.session_ms
        );
        assert!(
            concurrent.event_ms <= 500
                && concurrent.turn_ms <= 750
                && concurrent.session_ms <= 1_000,
            "concurrent open missed an SLA: {concurrent:?}"
        );
        assert!(
            recovery.event_ms <= 500 && recovery.turn_ms <= 750 && recovery.session_ms <= 1_000,
            "post-concurrency recovery missed an open SLA: {recovery:?}"
        );

        let metrics = read_open_cost_metrics(&clickhouse, database_name).await?;
        let before_cost = metrics
            .get("before")
            .context("before-corpus query-log metrics missing")?;
        let after_cost = metrics
            .get("after")
            .context("after-corpus query-log metrics missing")?;
        let concurrent_cost = metrics
            .get("concurrent")
            .context("concurrent query-log metrics missing")?;
        let recovery_cost = metrics
            .get("recovery")
            .context("recovery query-log metrics missing")?;

        assert_eq!(after_cost.query_count, before_cost.query_count);
        assert!(
            after_cost.read_rows <= before_cost.read_rows + READ_ROW_GROWTH_BUDGET,
            "unrelated corpus caused row growth: before={before_cost:?} after={after_cost:?}"
        );
        assert!(
            after_cost.read_rows < UNRELATED_EVENTS / 10,
            "open read rows grew linearly with unrelated events: {after_cost:?}"
        );
        assert!(
            after_cost.read_bytes <= before_cost.read_bytes + READ_BYTE_GROWTH_BUDGET,
            "unrelated corpus caused byte growth: before={before_cost:?} after={after_cost:?}"
        );
        assert!(
            after_cost.peak_memory <= before_cost.peak_memory + MEMORY_GROWTH_BUDGET,
            "unrelated corpus caused memory growth: before={before_cost:?} after={after_cost:?}"
        );
        assert_eq!(concurrent_cost.query_count, after_cost.query_count);
        assert_eq!(recovery_cost.query_count, after_cost.query_count);

        println!(
            "{}",
            json!({
                "benchmark_id": "mcp-open-boundedness",
                "unrelated_sessions": UNRELATED_SESSIONS,
                "unrelated_events": UNRELATED_EVENTS,
                "sequential": {
                    "before": {
                        "latency_ms": {
                            "event": before.event_ms,
                            "turn": before.turn_ms,
                            "session": before.session_ms,
                            "wall": before.wall_ms,
                        },
                        "throughput_opens_per_second": 3_000.0 / before.wall_ms.max(1) as f64,
                        "errors": 0,
                        "query_log": before_cost,
                    },
                    "after": {
                        "latency_ms": {
                            "event": after.event_ms,
                            "turn": after.turn_ms,
                            "session": after.session_ms,
                            "wall": after.wall_ms,
                        },
                        "throughput_opens_per_second": 3_000.0 / after.wall_ms.max(1) as f64,
                        "errors": 0,
                        "query_log": after_cost,
                    },
                    "recovery": {
                        "latency_ms": {
                            "event": recovery.event_ms,
                            "turn": recovery.turn_ms,
                            "session": recovery.session_ms,
                            "wall": recovery.wall_ms,
                        },
                        "throughput_opens_per_second": 3_000.0 / recovery.wall_ms.max(1) as f64,
                        "errors": 0,
                        "query_log": recovery_cost,
                    },
                },
                "concurrent": {
                    "latency_ms": {
                        "event": concurrent.event_ms,
                        "turn": concurrent.turn_ms,
                        "session": concurrent.session_ms,
                        "wall": concurrent.wall_ms,
                    },
                    "throughput_opens_per_second": if concurrent.wall_ms == 0 {
                        0.0
                    } else {
                        3_000.0 / concurrent.wall_ms as f64
                    },
                    "errors": 0,
                    "query_log": concurrent_cost,
                },
            })
        );
        Ok(())
    }
    .await;

    let cleanup = cleanup_database(&clickhouse, &database).await;
    let census =
        assert_owned_database_census_empty(&clickhouse, "after bounded-open benchmark").await;
    finish_with_cleanup(outcome, finish_with_cleanup(cleanup, census))
}

fn direct_analytics_semantics(
    snapshot: moraine_conversations::AnalyticsSnapshot,
) -> Result<SemanticObservation> {
    let payload = json!({
        "tokens": snapshot.tokens,
        "turns": snapshot.turns,
        "concurrent_sessions": snapshot.concurrent_sessions,
    });
    SemanticObservation::new(
        Cardinality::AnalyticsSeries {
            tokens: payload["tokens"].as_array().map_or(0, Vec::len),
            turns: payload["turns"].as_array().map_or(0, Vec::len),
            concurrent_sessions: payload["concurrent_sessions"]
                .as_array()
                .map_or(0, Vec::len),
        },
        &payload,
    )
}

fn direct_sessions_semantics(
    sessions: &[moraine_conversations::SessionAnalytics],
) -> Result<SemanticObservation> {
    let payload = Value::Array(
        sessions
            .iter()
            .map(|session| {
                json!({
                    "session_id": session.summary.session_id,
                    "harness": session.harness,
                    "started_at_unix_ms": session.summary.first_event_unix_ms,
                    "ended_at_unix_ms": session.summary.last_event_unix_ms,
                    "models": session.models,
                    "trace_id": session.trace_id,
                    "turns": session.turns.len(),
                    "tool_calls": session.summary.tool_calls,
                })
            })
            .collect(),
    );
    SemanticObservation::new(
        Cardinality::Sessions {
            sessions: sessions.len(),
        },
        &payload,
    )
}

async fn monitor_semantics<T: MonitorResponse>(
    client: &Client,
    url: &Url,
) -> Result<SemanticObservation> {
    let response = client
        .get(url.clone())
        .send()
        .await
        .with_context(|| format!("monitor request failed: {url}"))?;
    let status = response.status();
    let body = response.bytes().await.context("monitor body read failed")?;
    if !status.is_success() {
        bail!(
            "monitor returned HTTP {status}: {}",
            String::from_utf8_lossy(&body)
        );
    }
    serde_json::from_slice::<T>(&body)
        .context("monitor returned invalid JSON")?
        .into_semantics()
}

async fn start_owned_monitor(
    repository: ClickHouseConversationRepository,
) -> Result<(
    Url,
    oneshot::Sender<()>,
    tokio::task::JoinHandle<Result<()>>,
    std::path::PathBuf,
)> {
    let listener = tokio::net::TcpListener::bind("127.0.0.1:0")
        .await
        .context("failed to bind monitor listener")?;
    let port = listener.local_addr()?.port();

    let base = Url::parse(&format!("http://127.0.0.1:{port}/api/v1/"))?;
    let health_url = base.join("health")?;
    let client = Client::builder().timeout(Duration::from_secs(5)).build()?;
    let injected: Arc<dyn ConversationRepository> = Arc::new(repository);
    let router = Arc::new(BackendRepositoryRouter::from_preloaded_for_testing(
        Arc::new(AppConfig::default()),
        [(DEFAULT_BACKEND_NAME.to_string(), injected)],
    )?);

    let static_dir =
        env::temp_dir().join(format!("moraine-live-monitor-{}", Uuid::new_v4().simple()));
    fs::create_dir(&static_dir).context("failed to create monitor static directory")?;
    if let Err(error) = fs::write(static_dir.join("index.html"), "<!doctype html>") {
        let _ = fs::remove_dir_all(&static_dir);
        return Err(error).context("failed to create monitor static index");
    }

    let (shutdown_tx, shutdown_rx) = oneshot::channel();
    let server_static_dir = static_dir.clone();
    let server = tokio::spawn(async move {
        moraine_monitor_core::run_server_with_listener(
            router,
            listener,
            server_static_dir,
            async move {
                let _ = shutdown_rx.await;
            },
        )
        .await
    });
    let deadline = Instant::now() + Duration::from_secs(5);
    loop {
        match client.get(health_url.clone()).send().await {
            Ok(response) if response.status().is_success() => break,
            _ if Instant::now() < deadline => tokio::time::sleep(Duration::from_millis(20)).await,
            _ => {
                let _ = shutdown_tx.send(());
                let _ = server.await;
                let _ = fs::remove_dir_all(&static_dir);
                bail!("owned monitor did not become ready before timeout");
            }
        }
    }
    Ok((base, shutdown_tx, server, static_dir))
}

#[tokio::test]
#[ignore = "requires wrapper-owned live ClickHouse and destructive opt-in"]
async fn live_monitor_repository_semantic_parity() -> Result<()> {
    let prerequisites = LivePrerequisites::load()?;
    let database = prepare_owned_database_identity(&prerequisites.sandbox_id)?;
    let clickhouse = live_client(&prerequisites, &database)?;
    assert_owned_database_census_empty(&clickhouse, "before mutation").await?;

    let outcome = async {
        clickhouse
            .run_migrations()
            .await
            .context("failed to migrate parity database")?;
        install_schema_fixture(&clickhouse, &database).await?;

        let monitor_repository =
            ClickHouseConversationRepository::new(clickhouse.clone(), RepoConfig::default());
        let direct_repository =
            ClickHouseConversationRepository::new(clickhouse.clone(), RepoConfig::default());
        let client = Client::builder().timeout(Duration::from_secs(30)).build()?;
        let (base, shutdown, server, static_dir) = start_owned_monitor(monitor_repository).await?;

        let parity = async {
            let monitor_analytics = monitor_semantics::<MonitorAnalyticsResponse>(
                &client,
                &base.join("analytics?range=24h")?,
            )
            .await?;
            let direct_analytics = direct_analytics_semantics(
                direct_repository
                    .analytics_series(AnalyticsRange::TwentyFourHours)
                    .await?,
            )?;
            let analytics_comparison =
                SemanticComparison::compare(&monitor_analytics, &direct_analytics);
            if !analytics_comparison.passed() {
                bail!("monitor/repository analytics semantic mismatch: {analytics_comparison:?}");
            }

            let monitor_sessions = monitor_semantics::<MonitorSessionsResponse>(
                &client,
                &base.join("sessions?since=30d&limit=50")?,
            )
            .await?;
            let direct_sessions = direct_sessions_semantics(
                &direct_repository
                    .list_session_analytics(SessionAnalyticsQuery {
                        lookback: SessionLookback::ThirtyDays,
                        limit: 50,
                    })
                    .await?,
            )?;
            let sessions_comparison =
                SemanticComparison::compare(&monitor_sessions, &direct_sessions);
            if !sessions_comparison.passed() {
                bail!("monitor/repository sessions semantic mismatch: {sessions_comparison:?}");
            }
            Ok(())
        }
        .await;

        let _ = shutdown.send(());
        let server_result = match server.await {
            Ok(result) => result,
            Err(error) => Err(anyhow!("owned monitor task failed to join: {error}")),
        };
        let static_cleanup = fs::remove_dir_all(&static_dir)
            .context("failed to remove owned monitor static directory");
        let monitor_cleanup = finish_with_cleanup(server_result, static_cleanup);
        finish_with_cleanup(parity, monitor_cleanup)
    }
    .await;

    let cleanup = cleanup_database(&clickhouse, &database).await;
    let census = assert_owned_database_census_empty(&clickhouse, "after cleanup").await;
    finish_with_cleanup(outcome, finish_with_cleanup(cleanup, census))
}

#[cfg(test)]
mod tests {
    use super::*;

    const MARKER: &str = "# Generated by scripts/dev/sandbox/moraine-sandbox for sb-a1b2c3\n[clickhouse]\nurl = \"http://clickhouse:8123\"\ndatabase = \"moraine\"\n";

    #[test]
    fn destructive_prerequisites_fail_closed_before_sql() {
        assert!(validate_prerequisites("", "sb-a1b2c3", "http://clickhouse:8123", MARKER).is_err());
        assert!(
            validate_prerequisites("1", "sb-zzzzzz", "http://clickhouse:8123", MARKER).is_err()
        );
        assert!(validate_prerequisites("1", "sb-a1b2c3", "http://127.0.0.1:8123", MARKER).is_err());
        assert!(validate_prerequisites(
            "1",
            "sb-a1b2c3",
            "http://user:secret@clickhouse:8123",
            MARKER
        )
        .is_err());
        assert!(
            validate_prerequisites("1", "sb-a1b2c3", "http://clickhouse:8123", "wrong marker")
                .is_err()
        );
        validate_prerequisites("1", "sb-a1b2c3", "http://clickhouse:8123", MARKER).unwrap();
    }

    #[test]
    fn concurrent_live_bodies_generate_distinct_internal_database_identities() {
        use std::sync::Barrier;
        use std::thread;

        let start = Arc::new(Barrier::new(3));
        let handles = ["sb-a1b2c3", "sb-d4e5f6"].map(|sandbox_id| {
            let start = Arc::clone(&start);
            thread::spawn(move || {
                let mut diagnostic = Vec::new();
                start.wait();
                let database =
                    prepare_owned_database_identity_with_writer(sandbox_id, &mut diagnostic)
                        .unwrap();
                (sandbox_id, database, String::from_utf8(diagnostic).unwrap())
            })
        });
        start.wait();
        let [(first_sandbox, first, first_diagnostic), (second_sandbox, second, second_diagnostic)] =
            handles.map(|handle| handle.join().unwrap());

        assert_ne!(first, second);
        for (sandbox_id, database, diagnostic) in [
            (first_sandbox, first, first_diagnostic),
            (second_sandbox, second, second_diagnostic),
        ] {
            validate_owned_database_name(database.as_str()).unwrap();
            assert_eq!(database.as_str().len(), OWNED_DATABASE_PREFIX.len() + 32);
            assert!(diagnostic.starts_with(&format!(
                "live ClickHouse database: {}\n",
                database.as_str()
            )));
            assert!(diagnostic.contains(&format!("cleanup: sandbox={sandbox_id} ")));
            assert!(diagnostic.contains(&cleanup_statement(&database)));
        }

        for unsafe_name in [
            "",
            "moraine",
            "moraine_test_",
            "moraine_test_xyz",
            "moraine_test_ABCDEF0123456789abcdef0123456789",
            "other_0123456789abcdef0123456789abcdef",
            "moraine_test_0123456789abcdef0123456789abcde;DROP",
        ] {
            assert!(
                validate_owned_database_name(unsafe_name).is_err(),
                "accepted {unsafe_name:?}"
            );
        }
    }

    #[test]
    fn cleanup_statement_can_only_be_built_from_validated_owned_name() {
        let database = OwnedDatabaseName::generate();
        assert_eq!(
            cleanup_statement(&database),
            format!("DROP DATABASE IF EXISTS `{}` SYNC", database.as_str())
        );
    }

    #[test]
    fn cleanup_composition_preserves_original_and_cleanup_errors() {
        let original = finish_with_cleanup(Err(anyhow!("query failed")), Ok(()))
            .unwrap_err()
            .to_string();
        assert_eq!(original, "query failed");
        let cleanup = finish_with_cleanup(Ok(()), Err(anyhow!("drop failed")))
            .unwrap_err()
            .to_string();
        assert!(cleanup.contains("live ClickHouse teardown failed"));
        let both = finish_with_cleanup(
            Err(anyhow!("assertion failed")),
            Err(anyhow!("drop failed")),
        )
        .unwrap_err()
        .to_string();
        assert!(both.contains("assertion failed"));
        assert!(both.contains("drop failed"));
    }
}
