-- GENERATED by `reclaim_canonical::tests::fixture_dualuid_delete_script`; do
-- not hand-edit. Regenerate with MORAINE_UPDATE_RECLAIM_GOLDEN=1.
--
-- Run after `fixture_canonical_dualuid.sql` against the same `--path`. The
-- fixture holds ONE uid under TWO source names on one host — the uid material
-- excludes `source_name` (`sources/shared.rs`), so overlapping source
-- definitions share uids — with the `codex` attribution retired and the
-- `codexalt` attribution live. Every DELETE is
-- `emit_delete_statement(canonical_unit_predicates(unit))` verbatim for the one
-- unit the shipped probe returns, children first, `events` LAST. Identical
-- pinned-reader censuses at 'before', 'mid-unit' and 'after' — documents,
-- tool_io, event_links and the per-term df — are plan §7.2's G-DUALUID claim
-- executed in `clickhouse local`: the live name's rows all survive the retired
-- name's unit.

-- Unit-set agreement, checked BEFORE any delete runs. The unit list in
-- `reclaim_canonical.rs` is hand-maintained; the probe is the truth. If they
-- disagree this file aborts, having deleted nothing.
SELECT throwIf(
  arraySort(groupArray(concat(source_host, '/', source_name, '/', source_file, '/', toString(source_generation))))
    != ['h/codex//dup.jsonl/5'],
  'the fixture unit list no longer matches this build''s canonical_generation probe; the DELETE statements below are stale and the census that follows them is meaningless'
)
FROM (
WITH
  heads AS (
    SELECT source_host, source_name, source_file, source_generation, published_at
    FROM `moraine`.v_current_published_source_generations
  ),
  retired AS (
    SELECT h.source_host AS source_host, h.source_name AS source_name,
           h.source_file AS source_file, h.source_generation AS source_generation
    FROM `moraine`.v_published_source_generation_history AS h
    INNER JOIN heads AS head
      ON head.source_host = h.source_host
     AND head.source_name = h.source_name
     AND head.source_file = h.source_file
    WHERE h.source_generation != head.source_generation
      AND head.published_at < now64(3) - toIntervalSecond(604800)
  ),
  cg_rollup AS (
    SELECT source_host, source_name, source_file, source_generation,
         toUInt64(count()) AS event_rows, toUInt64(0) AS raw_rows,
         toUInt64(0) AS error_rows, toUInt64(0) AS document_rows
    FROM `moraine`.events
    WHERE (source_host, source_name, source_file, source_generation) IN (
      SELECT source_host, source_name, source_file, source_generation FROM retired
    )
    GROUP BY source_host, source_name, source_file, source_generation
    UNION ALL
    SELECT source_host, source_name, source_file, source_generation,
         toUInt64(0) AS event_rows, toUInt64(count()) AS raw_rows,
         toUInt64(0) AS error_rows, toUInt64(0) AS document_rows
    FROM `moraine`.raw_events
    WHERE (source_host, source_name, source_file, source_generation) IN (
      SELECT source_host, source_name, source_file, source_generation FROM retired
    )
    GROUP BY source_host, source_name, source_file, source_generation
    UNION ALL
    SELECT source_host, source_name, source_file, source_generation,
         toUInt64(0) AS event_rows, toUInt64(0) AS raw_rows,
         toUInt64(count()) AS error_rows, toUInt64(0) AS document_rows
    FROM `moraine`.ingest_errors
    WHERE (source_host, source_name, source_file, source_generation) IN (
      SELECT source_host, source_name, source_file, source_generation FROM retired
    )
    GROUP BY source_host, source_name, source_file, source_generation
    UNION ALL
    SELECT source_host, source_name, source_file, source_generation,
         toUInt64(0) AS event_rows, toUInt64(0) AS raw_rows,
         toUInt64(0) AS error_rows, toUInt64(count()) AS document_rows
    FROM `moraine`.search_documents
    WHERE (source_host, source_name, source_file, source_generation) IN (
      SELECT source_host, source_name, source_file, source_generation FROM retired
    )
    GROUP BY source_host, source_name, source_file, source_generation
  )
SELECT r.source_host AS source_host, r.source_name AS source_name,
       r.source_file AS source_file, toUInt32(r.source_generation) AS source_generation,
       toUInt64(sum(cg_rollup.event_rows)) AS event_rows,
       toUInt64(sum(cg_rollup.raw_rows)) AS raw_rows,
       toUInt64(sum(cg_rollup.error_rows)) AS error_rows,
       toUInt64(sum(cg_rollup.document_rows)) AS document_rows
FROM retired AS r
INNER JOIN cg_rollup ON cg_rollup.source_host = r.source_host
  AND cg_rollup.source_name = r.source_name
  AND cg_rollup.source_file = r.source_file
  AND cg_rollup.source_generation = r.source_generation
GROUP BY r.source_host, r.source_name, r.source_file, r.source_generation
ORDER BY source_host ASC, source_name ASC, source_file ASC, source_generation ASC
LIMIT 512
)
FORMAT Null;

SELECT 'before' AS at, src, toUInt64(count()) AS reader_visible_rows
FROM (
  SELECT 'events' AS src
  FROM (SELECT * FROM moraine.events FINAL) AS e
  ALL INNER JOIN moraine.v_current_published_source_generations AS h
    ON e.source_host = h.source_host AND e.source_name = h.source_name
   AND e.source_file = h.source_file AND e.source_generation = h.source_generation
  UNION ALL
  SELECT 'documents' AS src
  FROM (SELECT * FROM moraine.search_documents FINAL) AS d
  ALL INNER JOIN moraine.v_current_published_source_generations AS h
    ON d.source_host = h.source_host AND d.source_name = h.source_name
   AND d.source_file = h.source_file AND d.source_generation = h.source_generation
  WHERE d.doc_len > 0
  UNION ALL
  SELECT 'tool_io' AS src
  FROM (SELECT * FROM moraine.tool_io FINAL) AS t
  ALL INNER JOIN (
    SELECT e.source_host AS source_host, e.event_uid AS event_uid, e.event_version AS event_version
    FROM (SELECT * FROM moraine.events FINAL) AS e
    ALL INNER JOIN moraine.v_current_published_source_generations AS h
      ON e.source_host = h.source_host AND e.source_name = h.source_name
     AND e.source_file = h.source_file AND e.source_generation = h.source_generation
  ) AS le ON t.source_host = le.source_host AND t.event_uid = le.event_uid
   AND t.source_event_version != 0 AND t.source_event_version = le.event_version
  UNION ALL
  SELECT 'event_links' AS src
  FROM (SELECT * FROM moraine.event_links FINAL) AS l
  ALL INNER JOIN (
    SELECT e.source_host AS source_host, e.event_uid AS event_uid, e.event_version AS event_version
    FROM (SELECT * FROM moraine.events FINAL) AS e
    ALL INNER JOIN moraine.v_current_published_source_generations AS h
      ON e.source_host = h.source_host AND e.source_name = h.source_name
     AND e.source_file = h.source_file AND e.source_generation = h.source_generation
  ) AS le ON l.source_host = le.source_host AND l.event_uid = le.event_uid
   AND l.source_event_version != 0 AND l.source_event_version = le.event_version
)
GROUP BY src
ORDER BY src ASC
FORMAT TSVWithNames;

SELECT 'before' AS at, p.term AS term, toUInt64(count()) AS live_df
FROM (SELECT * FROM moraine.search_postings FINAL) AS p
ALL INNER JOIN (
  SELECT d.source_host AS source_host, d.source_name AS source_name,
         d.session_id AS session_id, d.source_ref AS source_ref,
         d.event_uid AS event_uid, d.doc_version AS doc_version
  FROM (SELECT * FROM moraine.search_documents FINAL) AS d
  ALL INNER JOIN moraine.v_current_published_source_generations AS h
    ON d.source_host = h.source_host AND d.source_name = h.source_name
   AND d.source_file = h.source_file AND d.source_generation = h.source_generation
  WHERE d.doc_len > 0
) AS d
  ON p.source_host = d.source_host AND p.source_name = d.source_name
 AND p.session_id = d.session_id AND p.source_ref = d.source_ref
 AND p.doc_id = d.event_uid AND p.post_version = d.doc_version
GROUP BY term
ORDER BY term ASC
FORMAT TSVWithNames;

-- delete 1: search_postings
DELETE FROM `moraine`.search_postings
WHERE source_host = 'h' AND source_name = 'codex' AND doc_id IN (SELECT event_uid FROM `moraine`.search_documents WHERE (source_host, source_name, source_file, source_generation) IN (('h', 'codex', '/dup.jsonl', toUInt32(5))));

-- delete 2: search_documents
DELETE FROM `moraine`.search_documents
WHERE (source_host, source_name, source_file, source_generation) IN (('h', 'codex', '/dup.jsonl', toUInt32(5)));

-- delete 3: tool_io
DELETE FROM `moraine`.tool_io
WHERE (source_host, source_name, event_uid) IN (SELECT source_host, source_name, event_uid FROM `moraine`.events WHERE (source_host, source_name, source_file, source_generation) IN (('h', 'codex', '/dup.jsonl', toUInt32(5))));

-- delete 4: event_links
DELETE FROM `moraine`.event_links
WHERE (source_host, source_name, event_uid) IN (SELECT source_host, source_name, event_uid FROM `moraine`.events WHERE (source_host, source_name, source_file, source_generation) IN (('h', 'codex', '/dup.jsonl', toUInt32(5))));

SELECT 'mid-unit' AS at, src, toUInt64(count()) AS reader_visible_rows
FROM (
  SELECT 'events' AS src
  FROM (SELECT * FROM moraine.events FINAL) AS e
  ALL INNER JOIN moraine.v_current_published_source_generations AS h
    ON e.source_host = h.source_host AND e.source_name = h.source_name
   AND e.source_file = h.source_file AND e.source_generation = h.source_generation
  UNION ALL
  SELECT 'documents' AS src
  FROM (SELECT * FROM moraine.search_documents FINAL) AS d
  ALL INNER JOIN moraine.v_current_published_source_generations AS h
    ON d.source_host = h.source_host AND d.source_name = h.source_name
   AND d.source_file = h.source_file AND d.source_generation = h.source_generation
  WHERE d.doc_len > 0
  UNION ALL
  SELECT 'tool_io' AS src
  FROM (SELECT * FROM moraine.tool_io FINAL) AS t
  ALL INNER JOIN (
    SELECT e.source_host AS source_host, e.event_uid AS event_uid, e.event_version AS event_version
    FROM (SELECT * FROM moraine.events FINAL) AS e
    ALL INNER JOIN moraine.v_current_published_source_generations AS h
      ON e.source_host = h.source_host AND e.source_name = h.source_name
     AND e.source_file = h.source_file AND e.source_generation = h.source_generation
  ) AS le ON t.source_host = le.source_host AND t.event_uid = le.event_uid
   AND t.source_event_version != 0 AND t.source_event_version = le.event_version
  UNION ALL
  SELECT 'event_links' AS src
  FROM (SELECT * FROM moraine.event_links FINAL) AS l
  ALL INNER JOIN (
    SELECT e.source_host AS source_host, e.event_uid AS event_uid, e.event_version AS event_version
    FROM (SELECT * FROM moraine.events FINAL) AS e
    ALL INNER JOIN moraine.v_current_published_source_generations AS h
      ON e.source_host = h.source_host AND e.source_name = h.source_name
     AND e.source_file = h.source_file AND e.source_generation = h.source_generation
  ) AS le ON l.source_host = le.source_host AND l.event_uid = le.event_uid
   AND l.source_event_version != 0 AND l.source_event_version = le.event_version
)
GROUP BY src
ORDER BY src ASC
FORMAT TSVWithNames;

SELECT 'mid-unit' AS at, p.term AS term, toUInt64(count()) AS live_df
FROM (SELECT * FROM moraine.search_postings FINAL) AS p
ALL INNER JOIN (
  SELECT d.source_host AS source_host, d.source_name AS source_name,
         d.session_id AS session_id, d.source_ref AS source_ref,
         d.event_uid AS event_uid, d.doc_version AS doc_version
  FROM (SELECT * FROM moraine.search_documents FINAL) AS d
  ALL INNER JOIN moraine.v_current_published_source_generations AS h
    ON d.source_host = h.source_host AND d.source_name = h.source_name
   AND d.source_file = h.source_file AND d.source_generation = h.source_generation
  WHERE d.doc_len > 0
) AS d
  ON p.source_host = d.source_host AND p.source_name = d.source_name
 AND p.session_id = d.session_id AND p.source_ref = d.source_ref
 AND p.doc_id = d.event_uid AND p.post_version = d.doc_version
GROUP BY term
ORDER BY term ASC
FORMAT TSVWithNames;

-- delete 5: ingest_errors
DELETE FROM `moraine`.ingest_errors
WHERE (source_host, source_name, source_file, source_generation) IN (('h', 'codex', '/dup.jsonl', toUInt32(5)));

-- delete 6: raw_events
DELETE FROM `moraine`.raw_events
WHERE (source_host, source_name, source_file, source_generation) IN (('h', 'codex', '/dup.jsonl', toUInt32(5)));

-- delete 7: events
DELETE FROM `moraine`.events
WHERE (source_host, source_name, source_file, source_generation) IN (('h', 'codex', '/dup.jsonl', toUInt32(5)));

SELECT 'after' AS at, src, toUInt64(count()) AS reader_visible_rows
FROM (
  SELECT 'events' AS src
  FROM (SELECT * FROM moraine.events FINAL) AS e
  ALL INNER JOIN moraine.v_current_published_source_generations AS h
    ON e.source_host = h.source_host AND e.source_name = h.source_name
   AND e.source_file = h.source_file AND e.source_generation = h.source_generation
  UNION ALL
  SELECT 'documents' AS src
  FROM (SELECT * FROM moraine.search_documents FINAL) AS d
  ALL INNER JOIN moraine.v_current_published_source_generations AS h
    ON d.source_host = h.source_host AND d.source_name = h.source_name
   AND d.source_file = h.source_file AND d.source_generation = h.source_generation
  WHERE d.doc_len > 0
  UNION ALL
  SELECT 'tool_io' AS src
  FROM (SELECT * FROM moraine.tool_io FINAL) AS t
  ALL INNER JOIN (
    SELECT e.source_host AS source_host, e.event_uid AS event_uid, e.event_version AS event_version
    FROM (SELECT * FROM moraine.events FINAL) AS e
    ALL INNER JOIN moraine.v_current_published_source_generations AS h
      ON e.source_host = h.source_host AND e.source_name = h.source_name
     AND e.source_file = h.source_file AND e.source_generation = h.source_generation
  ) AS le ON t.source_host = le.source_host AND t.event_uid = le.event_uid
   AND t.source_event_version != 0 AND t.source_event_version = le.event_version
  UNION ALL
  SELECT 'event_links' AS src
  FROM (SELECT * FROM moraine.event_links FINAL) AS l
  ALL INNER JOIN (
    SELECT e.source_host AS source_host, e.event_uid AS event_uid, e.event_version AS event_version
    FROM (SELECT * FROM moraine.events FINAL) AS e
    ALL INNER JOIN moraine.v_current_published_source_generations AS h
      ON e.source_host = h.source_host AND e.source_name = h.source_name
     AND e.source_file = h.source_file AND e.source_generation = h.source_generation
  ) AS le ON l.source_host = le.source_host AND l.event_uid = le.event_uid
   AND l.source_event_version != 0 AND l.source_event_version = le.event_version
)
GROUP BY src
ORDER BY src ASC
FORMAT TSVWithNames;

SELECT 'after' AS at, p.term AS term, toUInt64(count()) AS live_df
FROM (SELECT * FROM moraine.search_postings FINAL) AS p
ALL INNER JOIN (
  SELECT d.source_host AS source_host, d.source_name AS source_name,
         d.session_id AS session_id, d.source_ref AS source_ref,
         d.event_uid AS event_uid, d.doc_version AS doc_version
  FROM (SELECT * FROM moraine.search_documents FINAL) AS d
  ALL INNER JOIN moraine.v_current_published_source_generations AS h
    ON d.source_host = h.source_host AND d.source_name = h.source_name
   AND d.source_file = h.source_file AND d.source_generation = h.source_generation
  WHERE d.doc_len > 0
) AS d
  ON p.source_host = d.source_host AND p.source_name = d.source_name
 AND p.session_id = d.session_id AND p.source_ref = d.source_ref
 AND p.doc_id = d.event_uid AND p.post_version = d.doc_version
GROUP BY term
ORDER BY term ASC
FORMAT TSVWithNames;

SELECT 'after' AS at, src, gen_tag, toUInt64(count()) AS physical_rows
FROM (
  SELECT 'events' AS src, concat(source_file, '#', toString(source_generation), '@', source_name) AS gen_tag FROM moraine.events
  UNION ALL SELECT 'raw_events', concat(source_file, '#', toString(source_generation), '@', source_name) FROM moraine.raw_events
  UNION ALL SELECT 'ingest_errors', concat(source_file, '#', toString(source_generation), '@', source_name) FROM moraine.ingest_errors
  UNION ALL SELECT 'search_documents', concat(source_file, '#', toString(source_generation), '@', source_name) FROM moraine.search_documents
  UNION ALL SELECT 'search_postings', concat('uid:', substring(doc_id, 1, 2), '@', source_name) FROM moraine.search_postings
  UNION ALL SELECT 'tool_io', concat('uid:', substring(event_uid, 1, 2), '@', source_name) FROM moraine.tool_io
  UNION ALL SELECT 'event_links', concat('uid:', substring(event_uid, 1, 2), '@', source_name) FROM moraine.event_links
)
GROUP BY src, gen_tag
ORDER BY src ASC, gen_tag ASC
FORMAT TSVWithNames;
