-- GENERATED by `reclaim_mcp_open::tests::fixture_delete_script`; do not hand-edit.
-- Regenerate with MORAINE_UPDATE_RECLAIM_GOLDEN=1.
--
-- Run after `fixture.sql` against the same `--path`. Every statement below is
-- `emit_delete_statement(mcp_open_unit_predicates(unit))` verbatim, for every unit
-- the two shipped probes return against that fixture.

-- Unit-set agreement, checked BEFORE any delete runs. `FIXTURE_UNITS` in
-- `reclaim_mcp_open.rs` is hand-maintained; the probes are the truth. If they
-- disagree this file aborts, because a file whose DELETEs are generated from a
-- stale list reports "intact" for exactly the rows a real run would destroy.

-- mcp_open_orphan
SELECT throwIf(
  arraySort(groupArray(concat(session_id, '/', toString(candidate_generation))))
    != ['o-collect/100', 'o-plandone/105', 'o-planned/104', 'o-turnsonly/107'],
  'FIXTURE_UNITS no longer matches this build''s mcp_open_orphan probe; the DELETE statements below are stale and the census that follows them is meaningless'
)
FROM (
SELECT child.session_id AS session_id,
       toUInt64(child.candidate_generation) AS candidate_generation,
       toUInt64(sum(child.event_rows)) AS event_rows,
       toUInt64(sum(child.turn_rows)) AS turn_rows,
       toUInt64(0) AS header_rows
FROM (
    SELECT session_id, candidate_generation, toUInt64(count()) AS event_rows,
         toUInt64(0) AS turn_rows, max(projected_at) AS newest
    FROM `moraine`.mcp_open_events
    GROUP BY session_id, candidate_generation
    UNION ALL
    SELECT session_id, candidate_generation, toUInt64(0) AS event_rows,
         toUInt64(count()) AS turn_rows, max(projected_at) AS newest
    FROM `moraine`.mcp_open_turns
    GROUP BY session_id, candidate_generation
  ) AS child
WHERE (child.session_id, child.candidate_generation) NOT IN (
    SELECT session_id, generation FROM `moraine`.mcp_open_publication_headers
  )
  AND (child.session_id, child.candidate_generation) NOT IN (
    SELECT session_id, candidate_generation
    FROM `moraine`.mcp_open_backfill_plans FINAL
    WHERE phase != 4
  )
GROUP BY child.session_id, child.candidate_generation
HAVING max(child.newest) < now64(3) - toIntervalSecond(86400)
ORDER BY session_id ASC, candidate_generation ASC
LIMIT 512
)
FORMAT Null;

-- mcp_open_retired_lineage
SELECT throwIf(
  arraySort(groupArray(concat(session_id, '/', toString(candidate_generation))))
    != ['L-RETIRE/50', 'L-RETIRE/53'],
  'FIXTURE_UNITS no longer matches this build''s mcp_open_retired_lineage probe; the DELETE statements below are stale and the census that follows them is meaningless'
)
FROM (
WITH
  headers AS (
    SELECT session_id, generation, header_revision, tombstone,
           required_heads_fingerprint, dirty_revision, prepared_at, required_source_heads
    FROM `moraine`.mcp_open_publication_headers FINAL
  ),
  required AS (
    SELECT session_id, generation, head.1 AS source_host, head.2 AS source_name,
           head.3 AS source_file, head.4 AS source_generation
    FROM headers ARRAY JOIN required_source_heads AS head
  ),
  unpublished AS (
    SELECT DISTINCT session_id, generation
    FROM required
    WHERE (source_host, source_name, source_file, source_generation) NOT IN (
      SELECT source_host, source_name, source_file, source_generation
      FROM `moraine`.v_current_published_source_generations
    )
  ),
  live AS (
    SELECT h.session_id AS session_id, h.header_revision AS live_header_revision,
           h.generation AS live_generation,
           h.required_heads_fingerprint AS live_fingerprint, h.prepared_at AS live_prepared_at,
           d.dirty_revision AS current_dirty
    FROM headers AS h
    INNER JOIN (
      SELECT session_id, generation FROM `moraine`.mcp_open_sessions FINAL
    ) AS p ON p.session_id = h.session_id AND p.generation = h.generation
    INNER JOIN (
      SELECT session_id, dirty_revision FROM `moraine`.mcp_open_dirty_sessions FINAL
    ) AS d ON d.session_id = h.session_id
    WHERE h.tombstone = 0
      AND length(h.required_source_heads) > 0
      AND h.dirty_revision = d.dirty_revision
      AND (h.session_id, h.generation) NOT IN (SELECT session_id, generation FROM unpublished)
      AND h.prepared_at < now64(3) - toIntervalSecond(86400)
  ),
  retired AS (
    SELECT h.session_id AS session_id, h.generation AS generation
    FROM headers AS h
    INNER JOIN live AS l ON l.session_id = h.session_id
    WHERE h.generation != l.live_generation
    GROUP BY h.session_id, h.generation
    HAVING countIf(h.header_revision < l.live_header_revision
             AND h.dirty_revision < l.current_dirty
             AND h.required_heads_fingerprint != l.live_fingerprint) = count()
  ),
  child AS (
    SELECT session_id, candidate_generation, toUInt64(count()) AS event_rows,
         toUInt64(0) AS turn_rows, max(projected_at) AS newest
    FROM `moraine`.mcp_open_events
    GROUP BY session_id, candidate_generation
    UNION ALL
    SELECT session_id, candidate_generation, toUInt64(0) AS event_rows,
         toUInt64(count()) AS turn_rows, max(projected_at) AS newest
    FROM `moraine`.mcp_open_turns
    GROUP BY session_id, candidate_generation
  )
SELECT r.session_id AS session_id,
       toUInt64(r.generation) AS candidate_generation,
       toUInt64(sum(ifNull(child.event_rows, 0))) AS event_rows,
       toUInt64(sum(ifNull(child.turn_rows, 0))) AS turn_rows,
       toUInt64(1) AS header_rows
FROM retired AS r
LEFT JOIN child ON child.session_id = r.session_id
  AND child.candidate_generation = r.generation
GROUP BY r.session_id, r.generation
HAVING max(ifNull(child.newest, toDateTime64(0, 3))) < now64(3) - toIntervalSecond(86400)
ORDER BY session_id ASC, candidate_generation ASC
LIMIT 512
)
FORMAT Null;

-- unit: mcp_open_orphan o-collect/100
DELETE FROM `moraine`.mcp_open_events
WHERE (session_id, candidate_generation) IN (('o-collect', toUInt64(100)));
DELETE FROM `moraine`.mcp_open_turns
WHERE (session_id, candidate_generation) IN (('o-collect', toUInt64(100)));
DELETE FROM `moraine`.mcp_open_publication_headers
WHERE (session_id, generation) IN (('o-collect', toUInt64(100)));

-- unit: mcp_open_orphan o-plandone/105
DELETE FROM `moraine`.mcp_open_events
WHERE (session_id, candidate_generation) IN (('o-plandone', toUInt64(105)));
DELETE FROM `moraine`.mcp_open_turns
WHERE (session_id, candidate_generation) IN (('o-plandone', toUInt64(105)));
DELETE FROM `moraine`.mcp_open_publication_headers
WHERE (session_id, generation) IN (('o-plandone', toUInt64(105)));

-- unit: mcp_open_orphan o-planned/104
DELETE FROM `moraine`.mcp_open_events
WHERE (session_id, candidate_generation) IN (('o-planned', toUInt64(104)));
DELETE FROM `moraine`.mcp_open_turns
WHERE (session_id, candidate_generation) IN (('o-planned', toUInt64(104)));
DELETE FROM `moraine`.mcp_open_publication_headers
WHERE (session_id, generation) IN (('o-planned', toUInt64(104)));

-- unit: mcp_open_orphan o-turnsonly/107
DELETE FROM `moraine`.mcp_open_events
WHERE (session_id, candidate_generation) IN (('o-turnsonly', toUInt64(107)));
DELETE FROM `moraine`.mcp_open_turns
WHERE (session_id, candidate_generation) IN (('o-turnsonly', toUInt64(107)));
DELETE FROM `moraine`.mcp_open_publication_headers
WHERE (session_id, generation) IN (('o-turnsonly', toUInt64(107)));

-- unit: mcp_open_retired_lineage L-RETIRE/50
DELETE FROM `moraine`.mcp_open_events
WHERE (session_id, candidate_generation) IN (('L-RETIRE', toUInt64(50)));
DELETE FROM `moraine`.mcp_open_turns
WHERE (session_id, candidate_generation) IN (('L-RETIRE', toUInt64(50)));
DELETE FROM `moraine`.mcp_open_publication_headers
WHERE (session_id, generation) IN (('L-RETIRE', toUInt64(50)));

-- unit: mcp_open_retired_lineage L-RETIRE/53
DELETE FROM `moraine`.mcp_open_events
WHERE (session_id, candidate_generation) IN (('L-RETIRE', toUInt64(53)));
DELETE FROM `moraine`.mcp_open_turns
WHERE (session_id, candidate_generation) IN (('L-RETIRE', toUInt64(53)));
DELETE FROM `moraine`.mcp_open_publication_headers
WHERE (session_id, generation) IN (('L-RETIRE', toUInt64(53)));

-- Survivor census. The two rows that matter are `A1B` — two headers at one
-- generation, the live one — and `L-RETIRE` generation 60, the live pointer
-- target. Both must be untouched; see the expected block in fixture.sql.
SELECT session_id,
       toUInt64(countIf(src = 'header')) AS headers,
       toUInt64(countIf(src = 'turn')) AS turns,
       toUInt64(countIf(src = 'event')) AS events
FROM (
  SELECT session_id, generation AS gen, 'header' AS src FROM moraine.mcp_open_publication_headers
  UNION ALL SELECT session_id, candidate_generation AS gen, 'turn' AS src FROM moraine.mcp_open_turns
  UNION ALL SELECT session_id, candidate_generation AS gen, 'event' AS src FROM moraine.mcp_open_events
)
GROUP BY session_id
ORDER BY session_id ASC
FORMAT TSVWithNames
