-- GENERATED by `reclaim_read_index::tests::fixture_delete_script`; do not
-- hand-edit. Regenerate with MORAINE_UPDATE_RECLAIM_GOLDEN=1.
--
-- Run after `fixture_read_index.sql` against the same `--path`. Every DELETE is
-- `emit_delete_statement(read_index_unit_predicates(unit))` verbatim for every
-- unit the shipped probe returns against that fixture. The reader-visible
-- census re-runs BETWEEN two deletes of the unit: identical counts at 'before',
-- 'mid-unit' and 'after' are the proof that a reader pinned to the published
-- heads cannot observe a partially-reclaimed generation.

-- Unit-set agreement, checked BEFORE any delete runs. `FIXTURE_UNITS` in
-- `reclaim_read_index.rs` is hand-maintained; the probe is the truth. If they
-- disagree this file aborts, having deleted nothing.
SELECT throwIf(
  arraySort(groupArray(concat(source_host, '/', source_name, '/', source_file, '/', toString(source_generation))))
    != ['h/codex//live.jsonl/5'],
  'FIXTURE_UNITS no longer matches this build''s read_index_generation probe; the DELETE statements below are stale and the census that follows them is meaningless'
)
FROM (
WITH
  heads AS (
    SELECT source_host, source_name, source_file, source_generation, published_at
    FROM `moraine`.v_current_published_source_generations
  ),
  retired AS (
    SELECT h.source_host AS source_host, h.source_name AS source_name,
           h.source_file AS source_file, h.source_generation AS source_generation
    FROM `moraine`.v_published_source_generation_history AS h
    INNER JOIN heads AS head
      ON head.source_host = h.source_host
     AND head.source_name = h.source_name
     AND head.source_file = h.source_file
    WHERE h.source_generation != head.source_generation
      AND head.published_at < now64(3) - toIntervalSecond(86400)
  ),
  ri_rollup AS (
    SELECT source_host, source_name, source_file, source_generation,
         toUInt64(count()) AS navigation_rows, toUInt64(0) AS locator_rows,
         toUInt64(0) AS directory_rows
    FROM `moraine`.mcp_event_navigation
    WHERE (source_host, source_name, source_file, source_generation) IN (
      SELECT source_host, source_name, source_file, source_generation FROM retired
    )
    GROUP BY source_host, source_name, source_file, source_generation
    UNION ALL
    SELECT source_host, source_name, source_file, source_generation,
         toUInt64(0) AS navigation_rows, toUInt64(count()) AS locator_rows,
         toUInt64(0) AS directory_rows
    FROM `moraine`.mcp_event_locator
    WHERE (source_host, source_name, source_file, source_generation) IN (
      SELECT source_host, source_name, source_file, source_generation FROM retired
    )
    GROUP BY source_host, source_name, source_file, source_generation
    UNION ALL
    SELECT source_host, source_name, source_file, source_generation,
         toUInt64(0) AS navigation_rows, toUInt64(0) AS locator_rows,
         toUInt64(count()) AS directory_rows
    FROM `moraine`.mcp_session_directory
    WHERE (source_host, source_name, source_file, source_generation) IN (
      SELECT source_host, source_name, source_file, source_generation FROM retired
    )
    GROUP BY source_host, source_name, source_file, source_generation
  )
SELECT r.source_host AS source_host, r.source_name AS source_name,
       r.source_file AS source_file, toUInt32(r.source_generation) AS source_generation,
       toUInt64(sum(ri_rollup.navigation_rows)) AS navigation_rows,
       toUInt64(sum(ri_rollup.locator_rows)) AS locator_rows,
       toUInt64(sum(ri_rollup.directory_rows)) AS directory_rows
FROM retired AS r
INNER JOIN ri_rollup ON ri_rollup.source_host = r.source_host
  AND ri_rollup.source_name = r.source_name
  AND ri_rollup.source_file = r.source_file
  AND ri_rollup.source_generation = r.source_generation
GROUP BY r.source_host, r.source_name, r.source_file, r.source_generation
ORDER BY source_host ASC, source_name ASC, source_file ASC, source_generation ASC
LIMIT 512
)
FORMAT Null;

SELECT 'before' AS at, src, toUInt64(count()) AS reader_visible_rows
FROM (
  SELECT 'navigation' AS src, source_host, source_name, source_file, source_generation FROM moraine.mcp_event_navigation
  UNION ALL SELECT 'locator', source_host, source_name, source_file, source_generation FROM moraine.mcp_event_locator
  UNION ALL SELECT 'directory', source_host, source_name, source_file, source_generation FROM moraine.mcp_session_directory
)
WHERE (source_host, source_name, source_file, source_generation) IN (
  SELECT source_host, source_name, source_file, source_generation FROM moraine.v_current_published_source_generations
)
GROUP BY src
ORDER BY src ASC
FORMAT TSVWithNames;

-- unit: read_index_generation h/codex//live.jsonl/5
DELETE FROM `moraine`.mcp_event_navigation
WHERE (source_host, source_name, source_file, source_generation) IN (('h', 'codex', '/live.jsonl', toUInt32(5)));

SELECT 'mid-unit' AS at, src, toUInt64(count()) AS reader_visible_rows
FROM (
  SELECT 'navigation' AS src, source_host, source_name, source_file, source_generation FROM moraine.mcp_event_navigation
  UNION ALL SELECT 'locator', source_host, source_name, source_file, source_generation FROM moraine.mcp_event_locator
  UNION ALL SELECT 'directory', source_host, source_name, source_file, source_generation FROM moraine.mcp_session_directory
)
WHERE (source_host, source_name, source_file, source_generation) IN (
  SELECT source_host, source_name, source_file, source_generation FROM moraine.v_current_published_source_generations
)
GROUP BY src
ORDER BY src ASC
FORMAT TSVWithNames;

DELETE FROM `moraine`.mcp_event_locator
WHERE (source_host, source_name, source_file, source_generation) IN (('h', 'codex', '/live.jsonl', toUInt32(5)));
DELETE FROM `moraine`.mcp_session_directory
WHERE (source_host, source_name, source_file, source_generation) IN (('h', 'codex', '/live.jsonl', toUInt32(5)));

SELECT 'after' AS at, src, toUInt64(count()) AS reader_visible_rows
FROM (
  SELECT 'navigation' AS src, source_host, source_name, source_file, source_generation FROM moraine.mcp_event_navigation
  UNION ALL SELECT 'locator', source_host, source_name, source_file, source_generation FROM moraine.mcp_event_locator
  UNION ALL SELECT 'directory', source_host, source_name, source_file, source_generation FROM moraine.mcp_session_directory
)
WHERE (source_host, source_name, source_file, source_generation) IN (
  SELECT source_host, source_name, source_file, source_generation FROM moraine.v_current_published_source_generations
)
GROUP BY src
ORDER BY src ASC
FORMAT TSVWithNames;

-- Physical survivor census, per generation tuple. The retired generation
-- (/live.jsonl gen 5) must be gone from all three tables; every other
-- generation — the live head 6, both /fresh.jsonl generations (horizon), the
-- never-published /unpub.jsonl gen 2 and /nohead.jsonl gen 1 (R1) — intact.
SELECT source_file, toUInt32(source_generation) AS generation,
       toUInt64(countIf(src = 'navigation')) AS navigation,
       toUInt64(countIf(src = 'locator')) AS locator,
       toUInt64(countIf(src = 'directory')) AS directory
FROM (
  SELECT source_file, source_generation, 'navigation' AS src FROM moraine.mcp_event_navigation
  UNION ALL SELECT source_file, source_generation, 'locator' AS src FROM moraine.mcp_event_locator
  UNION ALL SELECT source_file, source_generation, 'directory' AS src FROM moraine.mcp_session_directory
)
GROUP BY source_file, source_generation
ORDER BY source_file ASC, generation ASC
FORMAT TSVWithNames
